// Code generated by MockGen. DO NOT EDIT.
// Source: internal/syllabus/repository/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/syllabus/repository/interface.go -destination=internal/syllabus/repository/mocks/mock.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"
	time "time"

	filter "github.com/Lapakin/edu-planner/internal/app/filter"
	domain "github.com/Lapakin/edu-planner/internal/domain"
	repository "github.com/Lapakin/edu-planner/internal/syllabus/repository"
	sqlx "github.com/jmoiron/sqlx"
	gomock "go.uber.org/mock/gomock"
)

// MockRepoManager is a mock of RepoManager interface.
type MockRepoManager struct {
	ctrl     *gomock.Controller
	recorder *MockRepoManagerMockRecorder
	isgomock struct{}
}

// MockRepoManagerMockRecorder is the mock recorder for MockRepoManager.
type MockRepoManagerMockRecorder struct {
	mock *MockRepoManager
}

// NewMockRepoManager creates a new mock instance.
func NewMockRepoManager(ctrl *gomock.Controller) *MockRepoManager {
	mock := &MockRepoManager{ctrl: ctrl}
	mock.recorder = &MockRepoManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepoManager) EXPECT() *MockRepoManagerMockRecorder {
	return m.recorder
}

// NewAcademicYearRepo mocks base method.
func (m *MockRepoManager) NewAcademicYearRepo(db sqlx.ExtContext) repository.AcademicYearRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewAcademicYearRepo", db)
	ret0, _ := ret[0].(repository.AcademicYearRepository)
	return ret0
}

// NewAcademicYearRepo indicates an expected call of NewAcademicYearRepo.
func (mr *MockRepoManagerMockRecorder) NewAcademicYearRepo(db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewAcademicYearRepo", reflect.TypeOf((*MockRepoManager)(nil).NewAcademicYearRepo), db)
}

// NewBellScheduleRepo mocks base method.
func (m *MockRepoManager) NewBellScheduleRepo(db sqlx.ExtContext) repository.BellScheduleRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewBellScheduleRepo", db)
	ret0, _ := ret[0].(repository.BellScheduleRepository)
	return ret0
}

// NewBellScheduleRepo indicates an expected call of NewBellScheduleRepo.
func (mr *MockRepoManagerMockRecorder) NewBellScheduleRepo(db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewBellScheduleRepo", reflect.TypeOf((*MockRepoManager)(nil).NewBellScheduleRepo), db)
}

// NewCycleCommitteeRepo mocks base method.
func (m *MockRepoManager) NewCycleCommitteeRepo(db sqlx.ExtContext) repository.CycleCommitteeRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewCycleCommitteeRepo", db)
	ret0, _ := ret[0].(repository.CycleCommitteeRepository)
	return ret0
}

// NewCycleCommitteeRepo indicates an expected call of NewCycleCommitteeRepo.
func (mr *MockRepoManagerMockRecorder) NewCycleCommitteeRepo(db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewCycleCommitteeRepo", reflect.TypeOf((*MockRepoManager)(nil).NewCycleCommitteeRepo), db)
}

// NewDepartmentRepo mocks base method.
func (m *MockRepoManager) NewDepartmentRepo(db sqlx.ExtContext) repository.DepartmentRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewDepartmentRepo", db)
	ret0, _ := ret[0].(repository.DepartmentRepository)
	return ret0
}

// NewDepartmentRepo indicates an expected call of NewDepartmentRepo.
func (mr *MockRepoManagerMockRecorder) NewDepartmentRepo(db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewDepartmentRepo", reflect.TypeOf((*MockRepoManager)(nil).NewDepartmentRepo), db)
}

// NewDisciplineRepo mocks base method.
func (m *MockRepoManager) NewDisciplineRepo(db sqlx.ExtContext) repository.DisciplineRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewDisciplineRepo", db)
	ret0, _ := ret[0].(repository.DisciplineRepository)
	return ret0
}

// NewDisciplineRepo indicates an expected call of NewDisciplineRepo.
func (mr *MockRepoManagerMockRecorder) NewDisciplineRepo(db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewDisciplineRepo", reflect.TypeOf((*MockRepoManager)(nil).NewDisciplineRepo), db)
}

// NewGroupRepo mocks base method.
func (m *MockRepoManager) NewGroupRepo(db sqlx.ExtContext) repository.GroupRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewGroupRepo", db)
	ret0, _ := ret[0].(repository.GroupRepository)
	return ret0
}

// NewGroupRepo indicates an expected call of NewGroupRepo.
func (mr *MockRepoManagerMockRecorder) NewGroupRepo(db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewGroupRepo", reflect.TypeOf((*MockRepoManager)(nil).NewGroupRepo), db)
}

// NewMessageRepo mocks base method.
func (m *MockRepoManager) NewMessageRepo(db sqlx.ExtContext) repository.MessageRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewMessageRepo", db)
	ret0, _ := ret[0].(repository.MessageRepository)
	return ret0
}

// NewMessageRepo indicates an expected call of NewMessageRepo.
func (mr *MockRepoManagerMockRecorder) NewMessageRepo(db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewMessageRepo", reflect.TypeOf((*MockRepoManager)(nil).NewMessageRepo), db)
}

// NewRoomRepo mocks base method.
func (m *MockRepoManager) NewRoomRepo(db sqlx.ExtContext) repository.RoomRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewRoomRepo", db)
	ret0, _ := ret[0].(repository.RoomRepository)
	return ret0
}

// NewRoomRepo indicates an expected call of NewRoomRepo.
func (mr *MockRepoManagerMockRecorder) NewRoomRepo(db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewRoomRepo", reflect.TypeOf((*MockRepoManager)(nil).NewRoomRepo), db)
}

// NewScheduleRestrictionRepo mocks base method.
func (m *MockRepoManager) NewScheduleRestrictionRepo(db sqlx.ExtContext) repository.ScheduleRestrictionRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewScheduleRestrictionRepo", db)
	ret0, _ := ret[0].(repository.ScheduleRestrictionRepository)
	return ret0
}

// NewScheduleRestrictionRepo indicates an expected call of NewScheduleRestrictionRepo.
func (mr *MockRepoManagerMockRecorder) NewScheduleRestrictionRepo(db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewScheduleRestrictionRepo", reflect.TypeOf((*MockRepoManager)(nil).NewScheduleRestrictionRepo), db)
}

// NewScheduleTemplateRepo mocks base method.
func (m *MockRepoManager) NewScheduleTemplateRepo(db sqlx.ExtContext) repository.ScheduleTemplateRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewScheduleTemplateRepo", db)
	ret0, _ := ret[0].(repository.ScheduleTemplateRepository)
	return ret0
}

// NewScheduleTemplateRepo indicates an expected call of NewScheduleTemplateRepo.
func (mr *MockRepoManagerMockRecorder) NewScheduleTemplateRepo(db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewScheduleTemplateRepo", reflect.TypeOf((*MockRepoManager)(nil).NewScheduleTemplateRepo), db)
}

// NewScheduleTemplateSettingRepo mocks base method.
func (m *MockRepoManager) NewScheduleTemplateSettingRepo(db sqlx.ExtContext) repository.ScheduleTemplateSettingRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewScheduleTemplateSettingRepo", db)
	ret0, _ := ret[0].(repository.ScheduleTemplateSettingRepository)
	return ret0
}

// NewScheduleTemplateSettingRepo indicates an expected call of NewScheduleTemplateSettingRepo.
func (mr *MockRepoManagerMockRecorder) NewScheduleTemplateSettingRepo(db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewScheduleTemplateSettingRepo", reflect.TypeOf((*MockRepoManager)(nil).NewScheduleTemplateSettingRepo), db)
}

// NewSemesterRepo mocks base method.
func (m *MockRepoManager) NewSemesterRepo(db sqlx.ExtContext) repository.SemesterRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewSemesterRepo", db)
	ret0, _ := ret[0].(repository.SemesterRepository)
	return ret0
}

// NewSemesterRepo indicates an expected call of NewSemesterRepo.
func (mr *MockRepoManagerMockRecorder) NewSemesterRepo(db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewSemesterRepo", reflect.TypeOf((*MockRepoManager)(nil).NewSemesterRepo), db)
}

// NewSpecialtyRepo mocks base method.
func (m *MockRepoManager) NewSpecialtyRepo(db sqlx.ExtContext) repository.SpecialtyRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewSpecialtyRepo", db)
	ret0, _ := ret[0].(repository.SpecialtyRepository)
	return ret0
}

// NewSpecialtyRepo indicates an expected call of NewSpecialtyRepo.
func (mr *MockRepoManagerMockRecorder) NewSpecialtyRepo(db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewSpecialtyRepo", reflect.TypeOf((*MockRepoManager)(nil).NewSpecialtyRepo), db)
}

// NewStudyPlanRepo mocks base method.
func (m *MockRepoManager) NewStudyPlanRepo(db sqlx.ExtContext) repository.StudyPlanRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewStudyPlanRepo", db)
	ret0, _ := ret[0].(repository.StudyPlanRepository)
	return ret0
}

// NewStudyPlanRepo indicates an expected call of NewStudyPlanRepo.
func (mr *MockRepoManagerMockRecorder) NewStudyPlanRepo(db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewStudyPlanRepo", reflect.TypeOf((*MockRepoManager)(nil).NewStudyPlanRepo), db)
}

// NewTeacherRepo mocks base method.
func (m *MockRepoManager) NewTeacherRepo(db sqlx.ExtContext) repository.TeacherRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewTeacherRepo", db)
	ret0, _ := ret[0].(repository.TeacherRepository)
	return ret0
}

// NewTeacherRepo indicates an expected call of NewTeacherRepo.
func (mr *MockRepoManagerMockRecorder) NewTeacherRepo(db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewTeacherRepo", reflect.TypeOf((*MockRepoManager)(nil).NewTeacherRepo), db)
}

// NewUserRepo mocks base method.
func (m *MockRepoManager) NewUserRepo(db sqlx.ExtContext) repository.UserRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewUserRepo", db)
	ret0, _ := ret[0].(repository.UserRepository)
	return ret0
}

// NewUserRepo indicates an expected call of NewUserRepo.
func (mr *MockRepoManagerMockRecorder) NewUserRepo(db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewUserRepo", reflect.TypeOf((*MockRepoManager)(nil).NewUserRepo), db)
}

// NewWorkloadAssignmentRepo mocks base method.
func (m *MockRepoManager) NewWorkloadAssignmentRepo(db sqlx.ExtContext) repository.WorkloadAssignmentRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewWorkloadAssignmentRepo", db)
	ret0, _ := ret[0].(repository.WorkloadAssignmentRepository)
	return ret0
}

// NewWorkloadAssignmentRepo indicates an expected call of NewWorkloadAssignmentRepo.
func (mr *MockRepoManagerMockRecorder) NewWorkloadAssignmentRepo(db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewWorkloadAssignmentRepo", reflect.TypeOf((*MockRepoManager)(nil).NewWorkloadAssignmentRepo), db)
}

// NewWorkloadDistributionRepo mocks base method.
func (m *MockRepoManager) NewWorkloadDistributionRepo(db sqlx.ExtContext) repository.WorkloadDistributionRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewWorkloadDistributionRepo", db)
	ret0, _ := ret[0].(repository.WorkloadDistributionRepository)
	return ret0
}

// NewWorkloadDistributionRepo indicates an expected call of NewWorkloadDistributionRepo.
func (mr *MockRepoManagerMockRecorder) NewWorkloadDistributionRepo(db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewWorkloadDistributionRepo", reflect.TypeOf((*MockRepoManager)(nil).NewWorkloadDistributionRepo), db)
}

// MockAcademicYearRepository is a mock of AcademicYearRepository interface.
type MockAcademicYearRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAcademicYearRepositoryMockRecorder
	isgomock struct{}
}

// MockAcademicYearRepositoryMockRecorder is the mock recorder for MockAcademicYearRepository.
type MockAcademicYearRepositoryMockRecorder struct {
	mock *MockAcademicYearRepository
}

// NewMockAcademicYearRepository creates a new mock instance.
func NewMockAcademicYearRepository(ctrl *gomock.Controller) *MockAcademicYearRepository {
	mock := &MockAcademicYearRepository{ctrl: ctrl}
	mock.recorder = &MockAcademicYearRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAcademicYearRepository) EXPECT() *MockAcademicYearRepositoryMockRecorder {
	return m.recorder
}

// ActivateAcademicYear mocks base method.
func (m *MockAcademicYearRepository) ActivateAcademicYear(ctx context.Context, id uint64, currentTime time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateAcademicYear", ctx, id, currentTime)
	ret0, _ := ret[0].(error)
	return ret0
}

// ActivateAcademicYear indicates an expected call of ActivateAcademicYear.
func (mr *MockAcademicYearRepositoryMockRecorder) ActivateAcademicYear(ctx, id, currentTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateAcademicYear", reflect.TypeOf((*MockAcademicYearRepository)(nil).ActivateAcademicYear), ctx, id, currentTime)
}

// CreateAcademicYear mocks base method.
func (m *MockAcademicYearRepository) CreateAcademicYear(ctx context.Context, academicYears domain.AcademicYears) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAcademicYear", ctx, academicYears)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAcademicYear indicates an expected call of CreateAcademicYear.
func (mr *MockAcademicYearRepositoryMockRecorder) CreateAcademicYear(ctx, academicYears any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAcademicYear", reflect.TypeOf((*MockAcademicYearRepository)(nil).CreateAcademicYear), ctx, academicYears)
}

// DeactivateAllAcademicYears mocks base method.
func (m *MockAcademicYearRepository) DeactivateAllAcademicYears(ctx context.Context, currentTime time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateAllAcademicYears", ctx, currentTime)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateAllAcademicYears indicates an expected call of DeactivateAllAcademicYears.
func (mr *MockAcademicYearRepositoryMockRecorder) DeactivateAllAcademicYears(ctx, currentTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateAllAcademicYears", reflect.TypeOf((*MockAcademicYearRepository)(nil).DeactivateAllAcademicYears), ctx, currentTime)
}

// DeleteAcademicYears mocks base method.
func (m *MockAcademicYearRepository) DeleteAcademicYears(ctx context.Context, ids []uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAcademicYears", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAcademicYears indicates an expected call of DeleteAcademicYears.
func (mr *MockAcademicYearRepositoryMockRecorder) DeleteAcademicYears(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAcademicYears", reflect.TypeOf((*MockAcademicYearRepository)(nil).DeleteAcademicYears), ctx, ids)
}

// FetchAcademicYears mocks base method.
func (m *MockAcademicYearRepository) FetchAcademicYears(ctx context.Context, filters filter.Filters) (domain.AcademicYears, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchAcademicYears", ctx, filters)
	ret0, _ := ret[0].(domain.AcademicYears)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchAcademicYears indicates an expected call of FetchAcademicYears.
func (mr *MockAcademicYearRepositoryMockRecorder) FetchAcademicYears(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchAcademicYears", reflect.TypeOf((*MockAcademicYearRepository)(nil).FetchAcademicYears), ctx, filters)
}

// GetAcademicYearByID mocks base method.
func (m *MockAcademicYearRepository) GetAcademicYearByID(ctx context.Context, id uint64) (*domain.AcademicYear, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAcademicYearByID", ctx, id)
	ret0, _ := ret[0].(*domain.AcademicYear)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAcademicYearByID indicates an expected call of GetAcademicYearByID.
func (mr *MockAcademicYearRepositoryMockRecorder) GetAcademicYearByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAcademicYearByID", reflect.TypeOf((*MockAcademicYearRepository)(nil).GetAcademicYearByID), ctx, id)
}

// UpdateAcademicYears mocks base method.
func (m *MockAcademicYearRepository) UpdateAcademicYears(ctx context.Context, academicYears domain.AcademicYears) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAcademicYears", ctx, academicYears)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAcademicYears indicates an expected call of UpdateAcademicYears.
func (mr *MockAcademicYearRepositoryMockRecorder) UpdateAcademicYears(ctx, academicYears any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAcademicYears", reflect.TypeOf((*MockAcademicYearRepository)(nil).UpdateAcademicYears), ctx, academicYears)
}

// MockSemesterRepository is a mock of SemesterRepository interface.
type MockSemesterRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSemesterRepositoryMockRecorder
	isgomock struct{}
}

// MockSemesterRepositoryMockRecorder is the mock recorder for MockSemesterRepository.
type MockSemesterRepositoryMockRecorder struct {
	mock *MockSemesterRepository
}

// NewMockSemesterRepository creates a new mock instance.
func NewMockSemesterRepository(ctrl *gomock.Controller) *MockSemesterRepository {
	mock := &MockSemesterRepository{ctrl: ctrl}
	mock.recorder = &MockSemesterRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSemesterRepository) EXPECT() *MockSemesterRepositoryMockRecorder {
	return m.recorder
}

// CreateSemesters mocks base method.
func (m *MockSemesterRepository) CreateSemesters(ctx context.Context, semesters domain.Semesters) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSemesters", ctx, semesters)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSemesters indicates an expected call of CreateSemesters.
func (mr *MockSemesterRepositoryMockRecorder) CreateSemesters(ctx, semesters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSemesters", reflect.TypeOf((*MockSemesterRepository)(nil).CreateSemesters), ctx, semesters)
}

// DeleteSemesters mocks base method.
func (m *MockSemesterRepository) DeleteSemesters(ctx context.Context, ids []uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSemesters", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSemesters indicates an expected call of DeleteSemesters.
func (mr *MockSemesterRepositoryMockRecorder) DeleteSemesters(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSemesters", reflect.TypeOf((*MockSemesterRepository)(nil).DeleteSemesters), ctx, ids)
}

// FetchSemesters mocks base method.
func (m *MockSemesterRepository) FetchSemesters(ctx context.Context, filters filter.Filters) (domain.Semesters, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchSemesters", ctx, filters)
	ret0, _ := ret[0].(domain.Semesters)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchSemesters indicates an expected call of FetchSemesters.
func (mr *MockSemesterRepositoryMockRecorder) FetchSemesters(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchSemesters", reflect.TypeOf((*MockSemesterRepository)(nil).FetchSemesters), ctx, filters)
}

// GetSemesterByID mocks base method.
func (m *MockSemesterRepository) GetSemesterByID(ctx context.Context, id uint64) (*domain.Semester, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSemesterByID", ctx, id)
	ret0, _ := ret[0].(*domain.Semester)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSemesterByID indicates an expected call of GetSemesterByID.
func (mr *MockSemesterRepositoryMockRecorder) GetSemesterByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSemesterByID", reflect.TypeOf((*MockSemesterRepository)(nil).GetSemesterByID), ctx, id)
}

// UpdateSemesters mocks base method.
func (m *MockSemesterRepository) UpdateSemesters(ctx context.Context, semesters domain.Semesters) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSemesters", ctx, semesters)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSemesters indicates an expected call of UpdateSemesters.
func (mr *MockSemesterRepositoryMockRecorder) UpdateSemesters(ctx, semesters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSemesters", reflect.TypeOf((*MockSemesterRepository)(nil).UpdateSemesters), ctx, semesters)
}

// MockDepartmentRepository is a mock of DepartmentRepository interface.
type MockDepartmentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDepartmentRepositoryMockRecorder
	isgomock struct{}
}

// MockDepartmentRepositoryMockRecorder is the mock recorder for MockDepartmentRepository.
type MockDepartmentRepositoryMockRecorder struct {
	mock *MockDepartmentRepository
}

// NewMockDepartmentRepository creates a new mock instance.
func NewMockDepartmentRepository(ctrl *gomock.Controller) *MockDepartmentRepository {
	mock := &MockDepartmentRepository{ctrl: ctrl}
	mock.recorder = &MockDepartmentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDepartmentRepository) EXPECT() *MockDepartmentRepositoryMockRecorder {
	return m.recorder
}

// AttachDepartmentsToAcademicYear mocks base method.
func (m *MockDepartmentRepository) AttachDepartmentsToAcademicYear(ctx context.Context, toAttach map[uint64]domain.Departments) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachDepartmentsToAcademicYear", ctx, toAttach)
	ret0, _ := ret[0].(error)
	return ret0
}

// AttachDepartmentsToAcademicYear indicates an expected call of AttachDepartmentsToAcademicYear.
func (mr *MockDepartmentRepositoryMockRecorder) AttachDepartmentsToAcademicYear(ctx, toAttach any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachDepartmentsToAcademicYear", reflect.TypeOf((*MockDepartmentRepository)(nil).AttachDepartmentsToAcademicYear), ctx, toAttach)
}

// CreateDepartments mocks base method.
func (m *MockDepartmentRepository) CreateDepartments(ctx context.Context, departments domain.Departments) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDepartments", ctx, departments)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDepartments indicates an expected call of CreateDepartments.
func (mr *MockDepartmentRepositoryMockRecorder) CreateDepartments(ctx, departments any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDepartments", reflect.TypeOf((*MockDepartmentRepository)(nil).CreateDepartments), ctx, departments)
}

// DeleteDepartments mocks base method.
func (m *MockDepartmentRepository) DeleteDepartments(ctx context.Context, ids []uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDepartments", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDepartments indicates an expected call of DeleteDepartments.
func (mr *MockDepartmentRepositoryMockRecorder) DeleteDepartments(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDepartments", reflect.TypeOf((*MockDepartmentRepository)(nil).DeleteDepartments), ctx, ids)
}

// FetchDepartments mocks base method.
func (m *MockDepartmentRepository) FetchDepartments(ctx context.Context, filters filter.Filters) (domain.Departments, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchDepartments", ctx, filters)
	ret0, _ := ret[0].(domain.Departments)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchDepartments indicates an expected call of FetchDepartments.
func (mr *MockDepartmentRepositoryMockRecorder) FetchDepartments(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchDepartments", reflect.TypeOf((*MockDepartmentRepository)(nil).FetchDepartments), ctx, filters)
}

// GetDepartmentByID mocks base method.
func (m *MockDepartmentRepository) GetDepartmentByID(ctx context.Context, id uint64) (*domain.Department, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDepartmentByID", ctx, id)
	ret0, _ := ret[0].(*domain.Department)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDepartmentByID indicates an expected call of GetDepartmentByID.
func (mr *MockDepartmentRepositoryMockRecorder) GetDepartmentByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDepartmentByID", reflect.TypeOf((*MockDepartmentRepository)(nil).GetDepartmentByID), ctx, id)
}

// UpdateDepartments mocks base method.
func (m *MockDepartmentRepository) UpdateDepartments(ctx context.Context, departments domain.Departments) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDepartments", ctx, departments)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDepartments indicates an expected call of UpdateDepartments.
func (mr *MockDepartmentRepositoryMockRecorder) UpdateDepartments(ctx, departments any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDepartments", reflect.TypeOf((*MockDepartmentRepository)(nil).UpdateDepartments), ctx, departments)
}

// MockRoomRepository is a mock of RoomRepository interface.
type MockRoomRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRoomRepositoryMockRecorder
	isgomock struct{}
}

// MockRoomRepositoryMockRecorder is the mock recorder for MockRoomRepository.
type MockRoomRepositoryMockRecorder struct {
	mock *MockRoomRepository
}

// NewMockRoomRepository creates a new mock instance.
func NewMockRoomRepository(ctrl *gomock.Controller) *MockRoomRepository {
	mock := &MockRoomRepository{ctrl: ctrl}
	mock.recorder = &MockRoomRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomRepository) EXPECT() *MockRoomRepositoryMockRecorder {
	return m.recorder
}

// AttachRoomsToAcademicYear mocks base method.
func (m *MockRoomRepository) AttachRoomsToAcademicYear(ctx context.Context, toAttach map[uint64]domain.Rooms) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachRoomsToAcademicYear", ctx, toAttach)
	ret0, _ := ret[0].(error)
	return ret0
}

// AttachRoomsToAcademicYear indicates an expected call of AttachRoomsToAcademicYear.
func (mr *MockRoomRepositoryMockRecorder) AttachRoomsToAcademicYear(ctx, toAttach any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachRoomsToAcademicYear", reflect.TypeOf((*MockRoomRepository)(nil).AttachRoomsToAcademicYear), ctx, toAttach)
}

// CreateRooms mocks base method.
func (m *MockRoomRepository) CreateRooms(ctx context.Context, rooms domain.Rooms) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRooms", ctx, rooms)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRooms indicates an expected call of CreateRooms.
func (mr *MockRoomRepositoryMockRecorder) CreateRooms(ctx, rooms any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRooms", reflect.TypeOf((*MockRoomRepository)(nil).CreateRooms), ctx, rooms)
}

// DeleteRooms mocks base method.
func (m *MockRoomRepository) DeleteRooms(ctx context.Context, ids []uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRooms", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRooms indicates an expected call of DeleteRooms.
func (mr *MockRoomRepositoryMockRecorder) DeleteRooms(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRooms", reflect.TypeOf((*MockRoomRepository)(nil).DeleteRooms), ctx, ids)
}

// FetchRooms mocks base method.
func (m *MockRoomRepository) FetchRooms(ctx context.Context, filters filter.Filters) (domain.Rooms, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchRooms", ctx, filters)
	ret0, _ := ret[0].(domain.Rooms)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchRooms indicates an expected call of FetchRooms.
func (mr *MockRoomRepositoryMockRecorder) FetchRooms(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchRooms", reflect.TypeOf((*MockRoomRepository)(nil).FetchRooms), ctx, filters)
}

// GetRoomByID mocks base method.
func (m *MockRoomRepository) GetRoomByID(ctx context.Context, id uint64) (*domain.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoomByID", ctx, id)
	ret0, _ := ret[0].(*domain.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoomByID indicates an expected call of GetRoomByID.
func (mr *MockRoomRepositoryMockRecorder) GetRoomByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoomByID", reflect.TypeOf((*MockRoomRepository)(nil).GetRoomByID), ctx, id)
}

// UpdateRooms mocks base method.
func (m *MockRoomRepository) UpdateRooms(ctx context.Context, rooms domain.Rooms) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRooms", ctx, rooms)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRooms indicates an expected call of UpdateRooms.
func (mr *MockRoomRepositoryMockRecorder) UpdateRooms(ctx, rooms any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRooms", reflect.TypeOf((*MockRoomRepository)(nil).UpdateRooms), ctx, rooms)
}

// MockSpecialtyRepository is a mock of SpecialtyRepository interface.
type MockSpecialtyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSpecialtyRepositoryMockRecorder
	isgomock struct{}
}

// MockSpecialtyRepositoryMockRecorder is the mock recorder for MockSpecialtyRepository.
type MockSpecialtyRepositoryMockRecorder struct {
	mock *MockSpecialtyRepository
}

// NewMockSpecialtyRepository creates a new mock instance.
func NewMockSpecialtyRepository(ctrl *gomock.Controller) *MockSpecialtyRepository {
	mock := &MockSpecialtyRepository{ctrl: ctrl}
	mock.recorder = &MockSpecialtyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpecialtyRepository) EXPECT() *MockSpecialtyRepositoryMockRecorder {
	return m.recorder
}

// AttachSpecialtiesToAcademicYear mocks base method.
func (m *MockSpecialtyRepository) AttachSpecialtiesToAcademicYear(ctx context.Context, toAttach map[uint64]domain.Specialties) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachSpecialtiesToAcademicYear", ctx, toAttach)
	ret0, _ := ret[0].(error)
	return ret0
}

// AttachSpecialtiesToAcademicYear indicates an expected call of AttachSpecialtiesToAcademicYear.
func (mr *MockSpecialtyRepositoryMockRecorder) AttachSpecialtiesToAcademicYear(ctx, toAttach any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachSpecialtiesToAcademicYear", reflect.TypeOf((*MockSpecialtyRepository)(nil).AttachSpecialtiesToAcademicYear), ctx, toAttach)
}

// CreateSpecialties mocks base method.
func (m *MockSpecialtyRepository) CreateSpecialties(ctx context.Context, specialities domain.Specialties) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSpecialties", ctx, specialities)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSpecialties indicates an expected call of CreateSpecialties.
func (mr *MockSpecialtyRepositoryMockRecorder) CreateSpecialties(ctx, specialities any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSpecialties", reflect.TypeOf((*MockSpecialtyRepository)(nil).CreateSpecialties), ctx, specialities)
}

// DeleteSpecialties mocks base method.
func (m *MockSpecialtyRepository) DeleteSpecialties(ctx context.Context, ids []uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSpecialties", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSpecialties indicates an expected call of DeleteSpecialties.
func (mr *MockSpecialtyRepositoryMockRecorder) DeleteSpecialties(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSpecialties", reflect.TypeOf((*MockSpecialtyRepository)(nil).DeleteSpecialties), ctx, ids)
}

// FetchSpecialties mocks base method.
func (m *MockSpecialtyRepository) FetchSpecialties(ctx context.Context, filters filter.Filters) (domain.Specialties, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchSpecialties", ctx, filters)
	ret0, _ := ret[0].(domain.Specialties)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchSpecialties indicates an expected call of FetchSpecialties.
func (mr *MockSpecialtyRepositoryMockRecorder) FetchSpecialties(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchSpecialties", reflect.TypeOf((*MockSpecialtyRepository)(nil).FetchSpecialties), ctx, filters)
}

// GetSpecialtyByID mocks base method.
func (m *MockSpecialtyRepository) GetSpecialtyByID(ctx context.Context, id uint64) (*domain.Specialty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSpecialtyByID", ctx, id)
	ret0, _ := ret[0].(*domain.Specialty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSpecialtyByID indicates an expected call of GetSpecialtyByID.
func (mr *MockSpecialtyRepositoryMockRecorder) GetSpecialtyByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSpecialtyByID", reflect.TypeOf((*MockSpecialtyRepository)(nil).GetSpecialtyByID), ctx, id)
}

// UpdateSpecialties mocks base method.
func (m *MockSpecialtyRepository) UpdateSpecialties(ctx context.Context, specialities domain.Specialties) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSpecialties", ctx, specialities)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSpecialties indicates an expected call of UpdateSpecialties.
func (mr *MockSpecialtyRepositoryMockRecorder) UpdateSpecialties(ctx, specialities any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSpecialties", reflect.TypeOf((*MockSpecialtyRepository)(nil).UpdateSpecialties), ctx, specialities)
}

// MockCycleCommitteeRepository is a mock of CycleCommitteeRepository interface.
type MockCycleCommitteeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCycleCommitteeRepositoryMockRecorder
	isgomock struct{}
}

// MockCycleCommitteeRepositoryMockRecorder is the mock recorder for MockCycleCommitteeRepository.
type MockCycleCommitteeRepositoryMockRecorder struct {
	mock *MockCycleCommitteeRepository
}

// NewMockCycleCommitteeRepository creates a new mock instance.
func NewMockCycleCommitteeRepository(ctrl *gomock.Controller) *MockCycleCommitteeRepository {
	mock := &MockCycleCommitteeRepository{ctrl: ctrl}
	mock.recorder = &MockCycleCommitteeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCycleCommitteeRepository) EXPECT() *MockCycleCommitteeRepositoryMockRecorder {
	return m.recorder
}

// AttachCycleCommitteesToAcademicYear mocks base method.
func (m *MockCycleCommitteeRepository) AttachCycleCommitteesToAcademicYear(ctx context.Context, toAttach map[uint64]domain.CycleCommittees) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachCycleCommitteesToAcademicYear", ctx, toAttach)
	ret0, _ := ret[0].(error)
	return ret0
}

// AttachCycleCommitteesToAcademicYear indicates an expected call of AttachCycleCommitteesToAcademicYear.
func (mr *MockCycleCommitteeRepositoryMockRecorder) AttachCycleCommitteesToAcademicYear(ctx, toAttach any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachCycleCommitteesToAcademicYear", reflect.TypeOf((*MockCycleCommitteeRepository)(nil).AttachCycleCommitteesToAcademicYear), ctx, toAttach)
}

// CreateCycleCommittees mocks base method.
func (m *MockCycleCommitteeRepository) CreateCycleCommittees(ctx context.Context, cycleCommittees domain.CycleCommittees) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCycleCommittees", ctx, cycleCommittees)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCycleCommittees indicates an expected call of CreateCycleCommittees.
func (mr *MockCycleCommitteeRepositoryMockRecorder) CreateCycleCommittees(ctx, cycleCommittees any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCycleCommittees", reflect.TypeOf((*MockCycleCommitteeRepository)(nil).CreateCycleCommittees), ctx, cycleCommittees)
}

// DeleteCycleCommittees mocks base method.
func (m *MockCycleCommitteeRepository) DeleteCycleCommittees(ctx context.Context, ids []uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCycleCommittees", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCycleCommittees indicates an expected call of DeleteCycleCommittees.
func (mr *MockCycleCommitteeRepositoryMockRecorder) DeleteCycleCommittees(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCycleCommittees", reflect.TypeOf((*MockCycleCommitteeRepository)(nil).DeleteCycleCommittees), ctx, ids)
}

// FetchCycleCommittees mocks base method.
func (m *MockCycleCommitteeRepository) FetchCycleCommittees(ctx context.Context, filters filter.Filters) (domain.CycleCommittees, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchCycleCommittees", ctx, filters)
	ret0, _ := ret[0].(domain.CycleCommittees)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchCycleCommittees indicates an expected call of FetchCycleCommittees.
func (mr *MockCycleCommitteeRepositoryMockRecorder) FetchCycleCommittees(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchCycleCommittees", reflect.TypeOf((*MockCycleCommitteeRepository)(nil).FetchCycleCommittees), ctx, filters)
}

// GetCycleCommitteeByID mocks base method.
func (m *MockCycleCommitteeRepository) GetCycleCommitteeByID(ctx context.Context, id uint64) (*domain.CycleCommittee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCycleCommitteeByID", ctx, id)
	ret0, _ := ret[0].(*domain.CycleCommittee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCycleCommitteeByID indicates an expected call of GetCycleCommitteeByID.
func (mr *MockCycleCommitteeRepositoryMockRecorder) GetCycleCommitteeByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCycleCommitteeByID", reflect.TypeOf((*MockCycleCommitteeRepository)(nil).GetCycleCommitteeByID), ctx, id)
}

// UpdateCycleCommittees mocks base method.
func (m *MockCycleCommitteeRepository) UpdateCycleCommittees(ctx context.Context, cycleCommittees domain.CycleCommittees) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCycleCommittees", ctx, cycleCommittees)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCycleCommittees indicates an expected call of UpdateCycleCommittees.
func (mr *MockCycleCommitteeRepositoryMockRecorder) UpdateCycleCommittees(ctx, cycleCommittees any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCycleCommittees", reflect.TypeOf((*MockCycleCommitteeRepository)(nil).UpdateCycleCommittees), ctx, cycleCommittees)
}

// MockTeacherRepository is a mock of TeacherRepository interface.
type MockTeacherRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTeacherRepositoryMockRecorder
	isgomock struct{}
}

// MockTeacherRepositoryMockRecorder is the mock recorder for MockTeacherRepository.
type MockTeacherRepositoryMockRecorder struct {
	mock *MockTeacherRepository
}

// NewMockTeacherRepository creates a new mock instance.
func NewMockTeacherRepository(ctrl *gomock.Controller) *MockTeacherRepository {
	mock := &MockTeacherRepository{ctrl: ctrl}
	mock.recorder = &MockTeacherRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeacherRepository) EXPECT() *MockTeacherRepositoryMockRecorder {
	return m.recorder
}

// AttachTeachersToAcademicYear mocks base method.
func (m *MockTeacherRepository) AttachTeachersToAcademicYear(ctx context.Context, toAttach map[uint64]domain.Teachers) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachTeachersToAcademicYear", ctx, toAttach)
	ret0, _ := ret[0].(error)
	return ret0
}

// AttachTeachersToAcademicYear indicates an expected call of AttachTeachersToAcademicYear.
func (mr *MockTeacherRepositoryMockRecorder) AttachTeachersToAcademicYear(ctx, toAttach any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachTeachersToAcademicYear", reflect.TypeOf((*MockTeacherRepository)(nil).AttachTeachersToAcademicYear), ctx, toAttach)
}

// CreateTeachers mocks base method.
func (m *MockTeacherRepository) CreateTeachers(ctx context.Context, teachers domain.Teachers) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTeachers", ctx, teachers)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTeachers indicates an expected call of CreateTeachers.
func (mr *MockTeacherRepositoryMockRecorder) CreateTeachers(ctx, teachers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTeachers", reflect.TypeOf((*MockTeacherRepository)(nil).CreateTeachers), ctx, teachers)
}

// DeleteTeachers mocks base method.
func (m *MockTeacherRepository) DeleteTeachers(ctx context.Context, ids []uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTeachers", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTeachers indicates an expected call of DeleteTeachers.
func (mr *MockTeacherRepositoryMockRecorder) DeleteTeachers(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTeachers", reflect.TypeOf((*MockTeacherRepository)(nil).DeleteTeachers), ctx, ids)
}

// FetchTeachers mocks base method.
func (m *MockTeacherRepository) FetchTeachers(ctx context.Context, filters filter.Filters) (domain.Teachers, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchTeachers", ctx, filters)
	ret0, _ := ret[0].(domain.Teachers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchTeachers indicates an expected call of FetchTeachers.
func (mr *MockTeacherRepositoryMockRecorder) FetchTeachers(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchTeachers", reflect.TypeOf((*MockTeacherRepository)(nil).FetchTeachers), ctx, filters)
}

// GetTeacherByID mocks base method.
func (m *MockTeacherRepository) GetTeacherByID(ctx context.Context, id uint64) (*domain.Teacher, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeacherByID", ctx, id)
	ret0, _ := ret[0].(*domain.Teacher)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeacherByID indicates an expected call of GetTeacherByID.
func (mr *MockTeacherRepositoryMockRecorder) GetTeacherByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeacherByID", reflect.TypeOf((*MockTeacherRepository)(nil).GetTeacherByID), ctx, id)
}

// UpdateTeachers mocks base method.
func (m *MockTeacherRepository) UpdateTeachers(ctx context.Context, teachers domain.Teachers) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTeachers", ctx, teachers)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTeachers indicates an expected call of UpdateTeachers.
func (mr *MockTeacherRepositoryMockRecorder) UpdateTeachers(ctx, teachers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTeachers", reflect.TypeOf((*MockTeacherRepository)(nil).UpdateTeachers), ctx, teachers)
}

// MockDisciplineRepository is a mock of DisciplineRepository interface.
type MockDisciplineRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDisciplineRepositoryMockRecorder
	isgomock struct{}
}

// MockDisciplineRepositoryMockRecorder is the mock recorder for MockDisciplineRepository.
type MockDisciplineRepositoryMockRecorder struct {
	mock *MockDisciplineRepository
}

// NewMockDisciplineRepository creates a new mock instance.
func NewMockDisciplineRepository(ctrl *gomock.Controller) *MockDisciplineRepository {
	mock := &MockDisciplineRepository{ctrl: ctrl}
	mock.recorder = &MockDisciplineRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDisciplineRepository) EXPECT() *MockDisciplineRepositoryMockRecorder {
	return m.recorder
}

// AttachDisciplinesToAcademicYear mocks base method.
func (m *MockDisciplineRepository) AttachDisciplinesToAcademicYear(ctx context.Context, toAttach map[uint64]domain.Disciplines) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachDisciplinesToAcademicYear", ctx, toAttach)
	ret0, _ := ret[0].(error)
	return ret0
}

// AttachDisciplinesToAcademicYear indicates an expected call of AttachDisciplinesToAcademicYear.
func (mr *MockDisciplineRepositoryMockRecorder) AttachDisciplinesToAcademicYear(ctx, toAttach any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachDisciplinesToAcademicYear", reflect.TypeOf((*MockDisciplineRepository)(nil).AttachDisciplinesToAcademicYear), ctx, toAttach)
}

// CreateDisciplines mocks base method.
func (m *MockDisciplineRepository) CreateDisciplines(ctx context.Context, disciplines domain.Disciplines) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDisciplines", ctx, disciplines)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDisciplines indicates an expected call of CreateDisciplines.
func (mr *MockDisciplineRepositoryMockRecorder) CreateDisciplines(ctx, disciplines any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDisciplines", reflect.TypeOf((*MockDisciplineRepository)(nil).CreateDisciplines), ctx, disciplines)
}

// DeleteDisciplines mocks base method.
func (m *MockDisciplineRepository) DeleteDisciplines(ctx context.Context, ids []uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDisciplines", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDisciplines indicates an expected call of DeleteDisciplines.
func (mr *MockDisciplineRepositoryMockRecorder) DeleteDisciplines(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDisciplines", reflect.TypeOf((*MockDisciplineRepository)(nil).DeleteDisciplines), ctx, ids)
}

// FetchDisciplines mocks base method.
func (m *MockDisciplineRepository) FetchDisciplines(ctx context.Context, filters filter.Filters) (domain.Disciplines, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchDisciplines", ctx, filters)
	ret0, _ := ret[0].(domain.Disciplines)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchDisciplines indicates an expected call of FetchDisciplines.
func (mr *MockDisciplineRepositoryMockRecorder) FetchDisciplines(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchDisciplines", reflect.TypeOf((*MockDisciplineRepository)(nil).FetchDisciplines), ctx, filters)
}

// GetDisciplineByID mocks base method.
func (m *MockDisciplineRepository) GetDisciplineByID(ctx context.Context, id uint64) (*domain.Discipline, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDisciplineByID", ctx, id)
	ret0, _ := ret[0].(*domain.Discipline)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDisciplineByID indicates an expected call of GetDisciplineByID.
func (mr *MockDisciplineRepositoryMockRecorder) GetDisciplineByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDisciplineByID", reflect.TypeOf((*MockDisciplineRepository)(nil).GetDisciplineByID), ctx, id)
}

// UpdateDisciplines mocks base method.
func (m *MockDisciplineRepository) UpdateDisciplines(ctx context.Context, disciplines domain.Disciplines) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDisciplines", ctx, disciplines)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDisciplines indicates an expected call of UpdateDisciplines.
func (mr *MockDisciplineRepositoryMockRecorder) UpdateDisciplines(ctx, disciplines any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDisciplines", reflect.TypeOf((*MockDisciplineRepository)(nil).UpdateDisciplines), ctx, disciplines)
}

// MockGroupRepository is a mock of GroupRepository interface.
type MockGroupRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGroupRepositoryMockRecorder
	isgomock struct{}
}

// MockGroupRepositoryMockRecorder is the mock recorder for MockGroupRepository.
type MockGroupRepositoryMockRecorder struct {
	mock *MockGroupRepository
}

// NewMockGroupRepository creates a new mock instance.
func NewMockGroupRepository(ctrl *gomock.Controller) *MockGroupRepository {
	mock := &MockGroupRepository{ctrl: ctrl}
	mock.recorder = &MockGroupRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGroupRepository) EXPECT() *MockGroupRepositoryMockRecorder {
	return m.recorder
}

// AttachGroupsToAcademicYear mocks base method.
func (m *MockGroupRepository) AttachGroupsToAcademicYear(ctx context.Context, toAttach map[uint64]domain.Groups) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachGroupsToAcademicYear", ctx, toAttach)
	ret0, _ := ret[0].(error)
	return ret0
}

// AttachGroupsToAcademicYear indicates an expected call of AttachGroupsToAcademicYear.
func (mr *MockGroupRepositoryMockRecorder) AttachGroupsToAcademicYear(ctx, toAttach any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachGroupsToAcademicYear", reflect.TypeOf((*MockGroupRepository)(nil).AttachGroupsToAcademicYear), ctx, toAttach)
}

// CreateGroupSemesters mocks base method.
func (m *MockGroupRepository) CreateGroupSemesters(ctx context.Context, groupSemesters domain.GroupSemesters) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGroupSemesters", ctx, groupSemesters)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateGroupSemesters indicates an expected call of CreateGroupSemesters.
func (mr *MockGroupRepositoryMockRecorder) CreateGroupSemesters(ctx, groupSemesters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGroupSemesters", reflect.TypeOf((*MockGroupRepository)(nil).CreateGroupSemesters), ctx, groupSemesters)
}

// CreateGroups mocks base method.
func (m *MockGroupRepository) CreateGroups(ctx context.Context, groups domain.Groups) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGroups", ctx, groups)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateGroups indicates an expected call of CreateGroups.
func (mr *MockGroupRepositoryMockRecorder) CreateGroups(ctx, groups any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGroups", reflect.TypeOf((*MockGroupRepository)(nil).CreateGroups), ctx, groups)
}

// DeleteGroupSemesters mocks base method.
func (m *MockGroupRepository) DeleteGroupSemesters(ctx context.Context, ids []uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGroupSemesters", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGroupSemesters indicates an expected call of DeleteGroupSemesters.
func (mr *MockGroupRepositoryMockRecorder) DeleteGroupSemesters(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGroupSemesters", reflect.TypeOf((*MockGroupRepository)(nil).DeleteGroupSemesters), ctx, ids)
}

// DeleteGroups mocks base method.
func (m *MockGroupRepository) DeleteGroups(ctx context.Context, ids []uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGroups", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGroups indicates an expected call of DeleteGroups.
func (mr *MockGroupRepositoryMockRecorder) DeleteGroups(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGroups", reflect.TypeOf((*MockGroupRepository)(nil).DeleteGroups), ctx, ids)
}

// FetchGroupSemesters mocks base method.
func (m *MockGroupRepository) FetchGroupSemesters(ctx context.Context, filters filter.Filters) (domain.GroupSemesters, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchGroupSemesters", ctx, filters)
	ret0, _ := ret[0].(domain.GroupSemesters)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchGroupSemesters indicates an expected call of FetchGroupSemesters.
func (mr *MockGroupRepositoryMockRecorder) FetchGroupSemesters(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchGroupSemesters", reflect.TypeOf((*MockGroupRepository)(nil).FetchGroupSemesters), ctx, filters)
}

// FetchGroups mocks base method.
func (m *MockGroupRepository) FetchGroups(ctx context.Context, filters filter.Filters) (domain.Groups, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchGroups", ctx, filters)
	ret0, _ := ret[0].(domain.Groups)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchGroups indicates an expected call of FetchGroups.
func (mr *MockGroupRepositoryMockRecorder) FetchGroups(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchGroups", reflect.TypeOf((*MockGroupRepository)(nil).FetchGroups), ctx, filters)
}

// GetGroupByID mocks base method.
func (m *MockGroupRepository) GetGroupByID(ctx context.Context, id uint64) (*domain.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupByID", ctx, id)
	ret0, _ := ret[0].(*domain.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupByID indicates an expected call of GetGroupByID.
func (mr *MockGroupRepositoryMockRecorder) GetGroupByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupByID", reflect.TypeOf((*MockGroupRepository)(nil).GetGroupByID), ctx, id)
}

// GetGroupSemesterByID mocks base method.
func (m *MockGroupRepository) GetGroupSemesterByID(ctx context.Context, id uint64) (*domain.GroupSemester, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupSemesterByID", ctx, id)
	ret0, _ := ret[0].(*domain.GroupSemester)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupSemesterByID indicates an expected call of GetGroupSemesterByID.
func (mr *MockGroupRepositoryMockRecorder) GetGroupSemesterByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupSemesterByID", reflect.TypeOf((*MockGroupRepository)(nil).GetGroupSemesterByID), ctx, id)
}

// UpdateGroupSemesters mocks base method.
func (m *MockGroupRepository) UpdateGroupSemesters(ctx context.Context, groupSemesters domain.GroupSemesters) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGroupSemesters", ctx, groupSemesters)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateGroupSemesters indicates an expected call of UpdateGroupSemesters.
func (mr *MockGroupRepositoryMockRecorder) UpdateGroupSemesters(ctx, groupSemesters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGroupSemesters", reflect.TypeOf((*MockGroupRepository)(nil).UpdateGroupSemesters), ctx, groupSemesters)
}

// UpdateGroups mocks base method.
func (m *MockGroupRepository) UpdateGroups(ctx context.Context, groups domain.Groups) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGroups", ctx, groups)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateGroups indicates an expected call of UpdateGroups.
func (mr *MockGroupRepositoryMockRecorder) UpdateGroups(ctx, groups any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGroups", reflect.TypeOf((*MockGroupRepository)(nil).UpdateGroups), ctx, groups)
}

// MockMessageRepository is a mock of MessageRepository interface.
type MockMessageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMessageRepositoryMockRecorder
	isgomock struct{}
}

// MockMessageRepositoryMockRecorder is the mock recorder for MockMessageRepository.
type MockMessageRepositoryMockRecorder struct {
	mock *MockMessageRepository
}

// NewMockMessageRepository creates a new mock instance.
func NewMockMessageRepository(ctrl *gomock.Controller) *MockMessageRepository {
	mock := &MockMessageRepository{ctrl: ctrl}
	mock.recorder = &MockMessageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageRepository) EXPECT() *MockMessageRepositoryMockRecorder {
	return m.recorder
}

// Write mocks base method.
func (m *MockMessageRepository) Write(ctx context.Context, massages domain.Massages) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", ctx, massages)
	ret0, _ := ret[0].(error)
	return ret0
}

// Write indicates an expected call of Write.
func (mr *MockMessageRepositoryMockRecorder) Write(ctx, massages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockMessageRepository)(nil).Write), ctx, massages)
}

// MockStudyPlanRepository is a mock of StudyPlanRepository interface.
type MockStudyPlanRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStudyPlanRepositoryMockRecorder
	isgomock struct{}
}

// MockStudyPlanRepositoryMockRecorder is the mock recorder for MockStudyPlanRepository.
type MockStudyPlanRepositoryMockRecorder struct {
	mock *MockStudyPlanRepository
}

// NewMockStudyPlanRepository creates a new mock instance.
func NewMockStudyPlanRepository(ctrl *gomock.Controller) *MockStudyPlanRepository {
	mock := &MockStudyPlanRepository{ctrl: ctrl}
	mock.recorder = &MockStudyPlanRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStudyPlanRepository) EXPECT() *MockStudyPlanRepositoryMockRecorder {
	return m.recorder
}

// CreateStudyPlans mocks base method.
func (m *MockStudyPlanRepository) CreateStudyPlans(ctx context.Context, studyPlans domain.StudyPlans) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStudyPlans", ctx, studyPlans)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateStudyPlans indicates an expected call of CreateStudyPlans.
func (mr *MockStudyPlanRepositoryMockRecorder) CreateStudyPlans(ctx, studyPlans any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStudyPlans", reflect.TypeOf((*MockStudyPlanRepository)(nil).CreateStudyPlans), ctx, studyPlans)
}

// DeleteStudyPlans mocks base method.
func (m *MockStudyPlanRepository) DeleteStudyPlans(ctx context.Context, ids []uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStudyPlans", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteStudyPlans indicates an expected call of DeleteStudyPlans.
func (mr *MockStudyPlanRepositoryMockRecorder) DeleteStudyPlans(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStudyPlans", reflect.TypeOf((*MockStudyPlanRepository)(nil).DeleteStudyPlans), ctx, ids)
}

// FetchStudyPlans mocks base method.
func (m *MockStudyPlanRepository) FetchStudyPlans(ctx context.Context, filters filter.Filters) (domain.StudyPlans, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchStudyPlans", ctx, filters)
	ret0, _ := ret[0].(domain.StudyPlans)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchStudyPlans indicates an expected call of FetchStudyPlans.
func (mr *MockStudyPlanRepositoryMockRecorder) FetchStudyPlans(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchStudyPlans", reflect.TypeOf((*MockStudyPlanRepository)(nil).FetchStudyPlans), ctx, filters)
}

// GetStudyPlanByID mocks base method.
func (m *MockStudyPlanRepository) GetStudyPlanByID(ctx context.Context, id uint64) (*domain.StudyPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudyPlanByID", ctx, id)
	ret0, _ := ret[0].(*domain.StudyPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudyPlanByID indicates an expected call of GetStudyPlanByID.
func (mr *MockStudyPlanRepositoryMockRecorder) GetStudyPlanByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudyPlanByID", reflect.TypeOf((*MockStudyPlanRepository)(nil).GetStudyPlanByID), ctx, id)
}

// UpdateStudyPlans mocks base method.
func (m *MockStudyPlanRepository) UpdateStudyPlans(ctx context.Context, studyPlans domain.StudyPlans) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStudyPlans", ctx, studyPlans)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStudyPlans indicates an expected call of UpdateStudyPlans.
func (mr *MockStudyPlanRepositoryMockRecorder) UpdateStudyPlans(ctx, studyPlans any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStudyPlans", reflect.TypeOf((*MockStudyPlanRepository)(nil).UpdateStudyPlans), ctx, studyPlans)
}

// MockWorkloadDistributionRepository is a mock of WorkloadDistributionRepository interface.
type MockWorkloadDistributionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWorkloadDistributionRepositoryMockRecorder
	isgomock struct{}
}

// MockWorkloadDistributionRepositoryMockRecorder is the mock recorder for MockWorkloadDistributionRepository.
type MockWorkloadDistributionRepositoryMockRecorder struct {
	mock *MockWorkloadDistributionRepository
}

// NewMockWorkloadDistributionRepository creates a new mock instance.
func NewMockWorkloadDistributionRepository(ctrl *gomock.Controller) *MockWorkloadDistributionRepository {
	mock := &MockWorkloadDistributionRepository{ctrl: ctrl}
	mock.recorder = &MockWorkloadDistributionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkloadDistributionRepository) EXPECT() *MockWorkloadDistributionRepositoryMockRecorder {
	return m.recorder
}

// CreateWorkloadDistributions mocks base method.
func (m *MockWorkloadDistributionRepository) CreateWorkloadDistributions(ctx context.Context, distributions domain.WorkloadDistributions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWorkloadDistributions", ctx, distributions)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWorkloadDistributions indicates an expected call of CreateWorkloadDistributions.
func (mr *MockWorkloadDistributionRepositoryMockRecorder) CreateWorkloadDistributions(ctx, distributions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWorkloadDistributions", reflect.TypeOf((*MockWorkloadDistributionRepository)(nil).CreateWorkloadDistributions), ctx, distributions)
}

// DeleteWorkloadDistributions mocks base method.
func (m *MockWorkloadDistributionRepository) DeleteWorkloadDistributions(ctx context.Context, ids []uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWorkloadDistributions", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWorkloadDistributions indicates an expected call of DeleteWorkloadDistributions.
func (mr *MockWorkloadDistributionRepositoryMockRecorder) DeleteWorkloadDistributions(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWorkloadDistributions", reflect.TypeOf((*MockWorkloadDistributionRepository)(nil).DeleteWorkloadDistributions), ctx, ids)
}

// FetchWorkloadDistributions mocks base method.
func (m *MockWorkloadDistributionRepository) FetchWorkloadDistributions(ctx context.Context, filters filter.Filters) (domain.WorkloadDistributions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchWorkloadDistributions", ctx, filters)
	ret0, _ := ret[0].(domain.WorkloadDistributions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchWorkloadDistributions indicates an expected call of FetchWorkloadDistributions.
func (mr *MockWorkloadDistributionRepositoryMockRecorder) FetchWorkloadDistributions(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchWorkloadDistributions", reflect.TypeOf((*MockWorkloadDistributionRepository)(nil).FetchWorkloadDistributions), ctx, filters)
}

// GetWorkloadDistributionByID mocks base method.
func (m *MockWorkloadDistributionRepository) GetWorkloadDistributionByID(ctx context.Context, id uint64) (*domain.WorkloadDistribution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkloadDistributionByID", ctx, id)
	ret0, _ := ret[0].(*domain.WorkloadDistribution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkloadDistributionByID indicates an expected call of GetWorkloadDistributionByID.
func (mr *MockWorkloadDistributionRepositoryMockRecorder) GetWorkloadDistributionByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkloadDistributionByID", reflect.TypeOf((*MockWorkloadDistributionRepository)(nil).GetWorkloadDistributionByID), ctx, id)
}

// UpdateWorkloadDistributions mocks base method.
func (m *MockWorkloadDistributionRepository) UpdateWorkloadDistributions(ctx context.Context, distributions domain.WorkloadDistributions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWorkloadDistributions", ctx, distributions)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWorkloadDistributions indicates an expected call of UpdateWorkloadDistributions.
func (mr *MockWorkloadDistributionRepositoryMockRecorder) UpdateWorkloadDistributions(ctx, distributions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWorkloadDistributions", reflect.TypeOf((*MockWorkloadDistributionRepository)(nil).UpdateWorkloadDistributions), ctx, distributions)
}

// MockWorkloadAssignmentRepository is a mock of WorkloadAssignmentRepository interface.
type MockWorkloadAssignmentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWorkloadAssignmentRepositoryMockRecorder
	isgomock struct{}
}

// MockWorkloadAssignmentRepositoryMockRecorder is the mock recorder for MockWorkloadAssignmentRepository.
type MockWorkloadAssignmentRepositoryMockRecorder struct {
	mock *MockWorkloadAssignmentRepository
}

// NewMockWorkloadAssignmentRepository creates a new mock instance.
func NewMockWorkloadAssignmentRepository(ctrl *gomock.Controller) *MockWorkloadAssignmentRepository {
	mock := &MockWorkloadAssignmentRepository{ctrl: ctrl}
	mock.recorder = &MockWorkloadAssignmentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkloadAssignmentRepository) EXPECT() *MockWorkloadAssignmentRepositoryMockRecorder {
	return m.recorder
}

// CreateWorkloadAssignments mocks base method.
func (m *MockWorkloadAssignmentRepository) CreateWorkloadAssignments(ctx context.Context, assignments domain.WorkloadAssignments) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWorkloadAssignments", ctx, assignments)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWorkloadAssignments indicates an expected call of CreateWorkloadAssignments.
func (mr *MockWorkloadAssignmentRepositoryMockRecorder) CreateWorkloadAssignments(ctx, assignments any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWorkloadAssignments", reflect.TypeOf((*MockWorkloadAssignmentRepository)(nil).CreateWorkloadAssignments), ctx, assignments)
}

// DeleteWorkloadAssignments mocks base method.
func (m *MockWorkloadAssignmentRepository) DeleteWorkloadAssignments(ctx context.Context, ids []uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWorkloadAssignments", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWorkloadAssignments indicates an expected call of DeleteWorkloadAssignments.
func (mr *MockWorkloadAssignmentRepositoryMockRecorder) DeleteWorkloadAssignments(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWorkloadAssignments", reflect.TypeOf((*MockWorkloadAssignmentRepository)(nil).DeleteWorkloadAssignments), ctx, ids)
}

// FetchWorkloadAssignments mocks base method.
func (m *MockWorkloadAssignmentRepository) FetchWorkloadAssignments(ctx context.Context, filters filter.Filters) (domain.WorkloadAssignments, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchWorkloadAssignments", ctx, filters)
	ret0, _ := ret[0].(domain.WorkloadAssignments)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchWorkloadAssignments indicates an expected call of FetchWorkloadAssignments.
func (mr *MockWorkloadAssignmentRepositoryMockRecorder) FetchWorkloadAssignments(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchWorkloadAssignments", reflect.TypeOf((*MockWorkloadAssignmentRepository)(nil).FetchWorkloadAssignments), ctx, filters)
}

// GetWorkloadAssignmentByID mocks base method.
func (m *MockWorkloadAssignmentRepository) GetWorkloadAssignmentByID(ctx context.Context, id uint64) (*domain.WorkloadAssignment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkloadAssignmentByID", ctx, id)
	ret0, _ := ret[0].(*domain.WorkloadAssignment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkloadAssignmentByID indicates an expected call of GetWorkloadAssignmentByID.
func (mr *MockWorkloadAssignmentRepositoryMockRecorder) GetWorkloadAssignmentByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkloadAssignmentByID", reflect.TypeOf((*MockWorkloadAssignmentRepository)(nil).GetWorkloadAssignmentByID), ctx, id)
}

// UpdateWorkloadAssignments mocks base method.
func (m *MockWorkloadAssignmentRepository) UpdateWorkloadAssignments(ctx context.Context, assignments domain.WorkloadAssignments) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWorkloadAssignments", ctx, assignments)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWorkloadAssignments indicates an expected call of UpdateWorkloadAssignments.
func (mr *MockWorkloadAssignmentRepositoryMockRecorder) UpdateWorkloadAssignments(ctx, assignments any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWorkloadAssignments", reflect.TypeOf((*MockWorkloadAssignmentRepository)(nil).UpdateWorkloadAssignments), ctx, assignments)
}

// MockScheduleTemplateSettingRepository is a mock of ScheduleTemplateSettingRepository interface.
type MockScheduleTemplateSettingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockScheduleTemplateSettingRepositoryMockRecorder
	isgomock struct{}
}

// MockScheduleTemplateSettingRepositoryMockRecorder is the mock recorder for MockScheduleTemplateSettingRepository.
type MockScheduleTemplateSettingRepositoryMockRecorder struct {
	mock *MockScheduleTemplateSettingRepository
}

// NewMockScheduleTemplateSettingRepository creates a new mock instance.
func NewMockScheduleTemplateSettingRepository(ctrl *gomock.Controller) *MockScheduleTemplateSettingRepository {
	mock := &MockScheduleTemplateSettingRepository{ctrl: ctrl}
	mock.recorder = &MockScheduleTemplateSettingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScheduleTemplateSettingRepository) EXPECT() *MockScheduleTemplateSettingRepositoryMockRecorder {
	return m.recorder
}

// CreateScheduleTemplateSettings mocks base method.
func (m *MockScheduleTemplateSettingRepository) CreateScheduleTemplateSettings(ctx context.Context, settings domain.ScheduleTemplateSettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateScheduleTemplateSettings", ctx, settings)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateScheduleTemplateSettings indicates an expected call of CreateScheduleTemplateSettings.
func (mr *MockScheduleTemplateSettingRepositoryMockRecorder) CreateScheduleTemplateSettings(ctx, settings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateScheduleTemplateSettings", reflect.TypeOf((*MockScheduleTemplateSettingRepository)(nil).CreateScheduleTemplateSettings), ctx, settings)
}

// DeleteScheduleTemplateSettings mocks base method.
func (m *MockScheduleTemplateSettingRepository) DeleteScheduleTemplateSettings(ctx context.Context, ids []uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteScheduleTemplateSettings", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteScheduleTemplateSettings indicates an expected call of DeleteScheduleTemplateSettings.
func (mr *MockScheduleTemplateSettingRepositoryMockRecorder) DeleteScheduleTemplateSettings(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteScheduleTemplateSettings", reflect.TypeOf((*MockScheduleTemplateSettingRepository)(nil).DeleteScheduleTemplateSettings), ctx, ids)
}

// FetchScheduleTemplateSettings mocks base method.
func (m *MockScheduleTemplateSettingRepository) FetchScheduleTemplateSettings(ctx context.Context, filters filter.Filters) (domain.ScheduleTemplateSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchScheduleTemplateSettings", ctx, filters)
	ret0, _ := ret[0].(domain.ScheduleTemplateSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchScheduleTemplateSettings indicates an expected call of FetchScheduleTemplateSettings.
func (mr *MockScheduleTemplateSettingRepositoryMockRecorder) FetchScheduleTemplateSettings(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchScheduleTemplateSettings", reflect.TypeOf((*MockScheduleTemplateSettingRepository)(nil).FetchScheduleTemplateSettings), ctx, filters)
}

// GetScheduleTemplateSettingByID mocks base method.
func (m *MockScheduleTemplateSettingRepository) GetScheduleTemplateSettingByID(ctx context.Context, id uint64) (*domain.ScheduleTemplateSetting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScheduleTemplateSettingByID", ctx, id)
	ret0, _ := ret[0].(*domain.ScheduleTemplateSetting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScheduleTemplateSettingByID indicates an expected call of GetScheduleTemplateSettingByID.
func (mr *MockScheduleTemplateSettingRepositoryMockRecorder) GetScheduleTemplateSettingByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScheduleTemplateSettingByID", reflect.TypeOf((*MockScheduleTemplateSettingRepository)(nil).GetScheduleTemplateSettingByID), ctx, id)
}

// UpdateScheduleTemplateSettings mocks base method.
func (m *MockScheduleTemplateSettingRepository) UpdateScheduleTemplateSettings(ctx context.Context, settings domain.ScheduleTemplateSettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateScheduleTemplateSettings", ctx, settings)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateScheduleTemplateSettings indicates an expected call of UpdateScheduleTemplateSettings.
func (mr *MockScheduleTemplateSettingRepositoryMockRecorder) UpdateScheduleTemplateSettings(ctx, settings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateScheduleTemplateSettings", reflect.TypeOf((*MockScheduleTemplateSettingRepository)(nil).UpdateScheduleTemplateSettings), ctx, settings)
}

// MockBellScheduleRepository is a mock of BellScheduleRepository interface.
type MockBellScheduleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBellScheduleRepositoryMockRecorder
	isgomock struct{}
}

// MockBellScheduleRepositoryMockRecorder is the mock recorder for MockBellScheduleRepository.
type MockBellScheduleRepositoryMockRecorder struct {
	mock *MockBellScheduleRepository
}

// NewMockBellScheduleRepository creates a new mock instance.
func NewMockBellScheduleRepository(ctrl *gomock.Controller) *MockBellScheduleRepository {
	mock := &MockBellScheduleRepository{ctrl: ctrl}
	mock.recorder = &MockBellScheduleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBellScheduleRepository) EXPECT() *MockBellScheduleRepositoryMockRecorder {
	return m.recorder
}

// CreateBellSchedules mocks base method.
func (m *MockBellScheduleRepository) CreateBellSchedules(ctx context.Context, schedules domain.BellSchedules) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBellSchedules", ctx, schedules)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBellSchedules indicates an expected call of CreateBellSchedules.
func (mr *MockBellScheduleRepositoryMockRecorder) CreateBellSchedules(ctx, schedules any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBellSchedules", reflect.TypeOf((*MockBellScheduleRepository)(nil).CreateBellSchedules), ctx, schedules)
}

// DeleteBellSchedules mocks base method.
func (m *MockBellScheduleRepository) DeleteBellSchedules(ctx context.Context, ids []uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBellSchedules", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBellSchedules indicates an expected call of DeleteBellSchedules.
func (mr *MockBellScheduleRepositoryMockRecorder) DeleteBellSchedules(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBellSchedules", reflect.TypeOf((*MockBellScheduleRepository)(nil).DeleteBellSchedules), ctx, ids)
}

// FetchBellSchedules mocks base method.
func (m *MockBellScheduleRepository) FetchBellSchedules(ctx context.Context, filters filter.Filters) (domain.BellSchedules, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchBellSchedules", ctx, filters)
	ret0, _ := ret[0].(domain.BellSchedules)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchBellSchedules indicates an expected call of FetchBellSchedules.
func (mr *MockBellScheduleRepositoryMockRecorder) FetchBellSchedules(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchBellSchedules", reflect.TypeOf((*MockBellScheduleRepository)(nil).FetchBellSchedules), ctx, filters)
}

// GetBellScheduleByID mocks base method.
func (m *MockBellScheduleRepository) GetBellScheduleByID(ctx context.Context, id uint64) (*domain.BellSchedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBellScheduleByID", ctx, id)
	ret0, _ := ret[0].(*domain.BellSchedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBellScheduleByID indicates an expected call of GetBellScheduleByID.
func (mr *MockBellScheduleRepositoryMockRecorder) GetBellScheduleByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBellScheduleByID", reflect.TypeOf((*MockBellScheduleRepository)(nil).GetBellScheduleByID), ctx, id)
}

// UpdateBellSchedules mocks base method.
func (m *MockBellScheduleRepository) UpdateBellSchedules(ctx context.Context, schedules domain.BellSchedules) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBellSchedules", ctx, schedules)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBellSchedules indicates an expected call of UpdateBellSchedules.
func (mr *MockBellScheduleRepositoryMockRecorder) UpdateBellSchedules(ctx, schedules any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBellSchedules", reflect.TypeOf((*MockBellScheduleRepository)(nil).UpdateBellSchedules), ctx, schedules)
}

// MockScheduleTemplateRepository is a mock of ScheduleTemplateRepository interface.
type MockScheduleTemplateRepository struct {
	ctrl     *gomock.Controller
	recorder *MockScheduleTemplateRepositoryMockRecorder
	isgomock struct{}
}

// MockScheduleTemplateRepositoryMockRecorder is the mock recorder for MockScheduleTemplateRepository.
type MockScheduleTemplateRepositoryMockRecorder struct {
	mock *MockScheduleTemplateRepository
}

// NewMockScheduleTemplateRepository creates a new mock instance.
func NewMockScheduleTemplateRepository(ctrl *gomock.Controller) *MockScheduleTemplateRepository {
	mock := &MockScheduleTemplateRepository{ctrl: ctrl}
	mock.recorder = &MockScheduleTemplateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScheduleTemplateRepository) EXPECT() *MockScheduleTemplateRepositoryMockRecorder {
	return m.recorder
}

// ActivateScheduleTemplate mocks base method.
func (m *MockScheduleTemplateRepository) ActivateScheduleTemplate(ctx context.Context, id uint64, t time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateScheduleTemplate", ctx, id, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// ActivateScheduleTemplate indicates an expected call of ActivateScheduleTemplate.
func (mr *MockScheduleTemplateRepositoryMockRecorder) ActivateScheduleTemplate(ctx, id, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateScheduleTemplate", reflect.TypeOf((*MockScheduleTemplateRepository)(nil).ActivateScheduleTemplate), ctx, id, t)
}

// CreateScheduleTemplate mocks base method.
func (m *MockScheduleTemplateRepository) CreateScheduleTemplate(ctx context.Context, template *domain.ScheduleTemplate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateScheduleTemplate", ctx, template)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateScheduleTemplate indicates an expected call of CreateScheduleTemplate.
func (mr *MockScheduleTemplateRepositoryMockRecorder) CreateScheduleTemplate(ctx, template any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateScheduleTemplate", reflect.TypeOf((*MockScheduleTemplateRepository)(nil).CreateScheduleTemplate), ctx, template)
}

// DeleteScheduleTemplates mocks base method.
func (m *MockScheduleTemplateRepository) DeleteScheduleTemplates(ctx context.Context, ids []uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteScheduleTemplates", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteScheduleTemplates indicates an expected call of DeleteScheduleTemplates.
func (mr *MockScheduleTemplateRepositoryMockRecorder) DeleteScheduleTemplates(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteScheduleTemplates", reflect.TypeOf((*MockScheduleTemplateRepository)(nil).DeleteScheduleTemplates), ctx, ids)
}

// FetchScheduleTemplates mocks base method.
func (m *MockScheduleTemplateRepository) FetchScheduleTemplates(ctx context.Context, filters filter.Filters) (domain.ScheduleTemplates, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchScheduleTemplates", ctx, filters)
	ret0, _ := ret[0].(domain.ScheduleTemplates)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchScheduleTemplates indicates an expected call of FetchScheduleTemplates.
func (mr *MockScheduleTemplateRepositoryMockRecorder) FetchScheduleTemplates(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchScheduleTemplates", reflect.TypeOf((*MockScheduleTemplateRepository)(nil).FetchScheduleTemplates), ctx, filters)
}

// GetScheduleTemplateByID mocks base method.
func (m *MockScheduleTemplateRepository) GetScheduleTemplateByID(ctx context.Context, id uint64) (*domain.ScheduleTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScheduleTemplateByID", ctx, id)
	ret0, _ := ret[0].(*domain.ScheduleTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScheduleTemplateByID indicates an expected call of GetScheduleTemplateByID.
func (mr *MockScheduleTemplateRepositoryMockRecorder) GetScheduleTemplateByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScheduleTemplateByID", reflect.TypeOf((*MockScheduleTemplateRepository)(nil).GetScheduleTemplateByID), ctx, id)
}

// UpdateScheduleTemplate mocks base method.
func (m *MockScheduleTemplateRepository) UpdateScheduleTemplate(ctx context.Context, template *domain.ScheduleTemplate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateScheduleTemplate", ctx, template)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateScheduleTemplate indicates an expected call of UpdateScheduleTemplate.
func (mr *MockScheduleTemplateRepositoryMockRecorder) UpdateScheduleTemplate(ctx, template any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateScheduleTemplate", reflect.TypeOf((*MockScheduleTemplateRepository)(nil).UpdateScheduleTemplate), ctx, template)
}

// MockScheduleRestrictionRepository is a mock of ScheduleRestrictionRepository interface.
type MockScheduleRestrictionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockScheduleRestrictionRepositoryMockRecorder
	isgomock struct{}
}

// MockScheduleRestrictionRepositoryMockRecorder is the mock recorder for MockScheduleRestrictionRepository.
type MockScheduleRestrictionRepositoryMockRecorder struct {
	mock *MockScheduleRestrictionRepository
}

// NewMockScheduleRestrictionRepository creates a new mock instance.
func NewMockScheduleRestrictionRepository(ctrl *gomock.Controller) *MockScheduleRestrictionRepository {
	mock := &MockScheduleRestrictionRepository{ctrl: ctrl}
	mock.recorder = &MockScheduleRestrictionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScheduleRestrictionRepository) EXPECT() *MockScheduleRestrictionRepositoryMockRecorder {
	return m.recorder
}

// CreateScheduleRestrictions mocks base method.
func (m *MockScheduleRestrictionRepository) CreateScheduleRestrictions(ctx context.Context, restrictions domain.ScheduleRestrictions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateScheduleRestrictions", ctx, restrictions)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateScheduleRestrictions indicates an expected call of CreateScheduleRestrictions.
func (mr *MockScheduleRestrictionRepositoryMockRecorder) CreateScheduleRestrictions(ctx, restrictions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateScheduleRestrictions", reflect.TypeOf((*MockScheduleRestrictionRepository)(nil).CreateScheduleRestrictions), ctx, restrictions)
}

// DeleteScheduleRestrictions mocks base method.
func (m *MockScheduleRestrictionRepository) DeleteScheduleRestrictions(ctx context.Context, ids []uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteScheduleRestrictions", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteScheduleRestrictions indicates an expected call of DeleteScheduleRestrictions.
func (mr *MockScheduleRestrictionRepositoryMockRecorder) DeleteScheduleRestrictions(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteScheduleRestrictions", reflect.TypeOf((*MockScheduleRestrictionRepository)(nil).DeleteScheduleRestrictions), ctx, ids)
}

// FetchScheduleRestrictions mocks base method.
func (m *MockScheduleRestrictionRepository) FetchScheduleRestrictions(ctx context.Context, filters filter.Filters) (domain.ScheduleRestrictions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchScheduleRestrictions", ctx, filters)
	ret0, _ := ret[0].(domain.ScheduleRestrictions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchScheduleRestrictions indicates an expected call of FetchScheduleRestrictions.
func (mr *MockScheduleRestrictionRepositoryMockRecorder) FetchScheduleRestrictions(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchScheduleRestrictions", reflect.TypeOf((*MockScheduleRestrictionRepository)(nil).FetchScheduleRestrictions), ctx, filters)
}

// GetScheduleRestrictionByID mocks base method.
func (m *MockScheduleRestrictionRepository) GetScheduleRestrictionByID(ctx context.Context, id uint64) (*domain.ScheduleRestriction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScheduleRestrictionByID", ctx, id)
	ret0, _ := ret[0].(*domain.ScheduleRestriction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScheduleRestrictionByID indicates an expected call of GetScheduleRestrictionByID.
func (mr *MockScheduleRestrictionRepositoryMockRecorder) GetScheduleRestrictionByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScheduleRestrictionByID", reflect.TypeOf((*MockScheduleRestrictionRepository)(nil).GetScheduleRestrictionByID), ctx, id)
}

// UpdateScheduleRestrictions mocks base method.
func (m *MockScheduleRestrictionRepository) UpdateScheduleRestrictions(ctx context.Context, restrictions domain.ScheduleRestrictions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateScheduleRestrictions", ctx, restrictions)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateScheduleRestrictions indicates an expected call of UpdateScheduleRestrictions.
func (mr *MockScheduleRestrictionRepositoryMockRecorder) UpdateScheduleRestrictions(ctx, restrictions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateScheduleRestrictions", reflect.TypeOf((*MockScheduleRestrictionRepository)(nil).UpdateScheduleRestrictions), ctx, restrictions)
}

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// DeleteUser mocks base method.
func (m *MockUserRepository) DeleteUser(ctx context.Context, id uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockUserRepositoryMockRecorder) DeleteUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockUserRepository)(nil).DeleteUser), ctx, id)
}

// UpsertUser mocks base method.
func (m *MockUserRepository) UpsertUser(ctx context.Context, user *domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertUser indicates an expected call of UpsertUser.
func (mr *MockUserRepositoryMockRecorder) UpsertUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertUser", reflect.TypeOf((*MockUserRepository)(nil).UpsertUser), ctx, user)
}
