// Code generated by MockGen. DO NOT EDIT.
// Source: internal/user-management/repository/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/user-management/repository/interface.go -destination=internal/user-management/repository/mocks/mock.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"
	time "time"

	filter "github.com/Lapakin/edu-planner/internal/app/filter"
	domain "github.com/Lapakin/edu-planner/internal/domain"
	repository "github.com/Lapakin/edu-planner/internal/user-management/repository"
	sqlx "github.com/jmoiron/sqlx"
	gomock "go.uber.org/mock/gomock"
)

// MockRepoManager is a mock of RepoManager interface.
type MockRepoManager struct {
	ctrl     *gomock.Controller
	recorder *MockRepoManagerMockRecorder
	isgomock struct{}
}

// MockRepoManagerMockRecorder is the mock recorder for MockRepoManager.
type MockRepoManagerMockRecorder struct {
	mock *MockRepoManager
}

// NewMockRepoManager creates a new mock instance.
func NewMockRepoManager(ctrl *gomock.Controller) *MockRepoManager {
	mock := &MockRepoManager{ctrl: ctrl}
	mock.recorder = &MockRepoManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepoManager) EXPECT() *MockRepoManagerMockRecorder {
	return m.recorder
}

// NewAcademicYearRepo mocks base method.
func (m *MockRepoManager) NewAcademicYearRepo(db sqlx.ExtContext) repository.AcademicYearRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewAcademicYearRepo", db)
	ret0, _ := ret[0].(repository.AcademicYearRepository)
	return ret0
}

// NewAcademicYearRepo indicates an expected call of NewAcademicYearRepo.
func (mr *MockRepoManagerMockRecorder) NewAcademicYearRepo(db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewAcademicYearRepo", reflect.TypeOf((*MockRepoManager)(nil).NewAcademicYearRepo), db)
}

// NewAuthRepo mocks base method.
func (m *MockRepoManager) NewAuthRepo(db sqlx.ExtContext) repository.AuthRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewAuthRepo", db)
	ret0, _ := ret[0].(repository.AuthRepository)
	return ret0
}

// NewAuthRepo indicates an expected call of NewAuthRepo.
func (mr *MockRepoManagerMockRecorder) NewAuthRepo(db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewAuthRepo", reflect.TypeOf((*MockRepoManager)(nil).NewAuthRepo), db)
}

// NewMessageRepo mocks base method.
func (m *MockRepoManager) NewMessageRepo(db sqlx.ExtContext) repository.MessageRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewMessageRepo", db)
	ret0, _ := ret[0].(repository.MessageRepository)
	return ret0
}

// NewMessageRepo indicates an expected call of NewMessageRepo.
func (mr *MockRepoManagerMockRecorder) NewMessageRepo(db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewMessageRepo", reflect.TypeOf((*MockRepoManager)(nil).NewMessageRepo), db)
}

// NewUserRepo mocks base method.
func (m *MockRepoManager) NewUserRepo(db sqlx.ExtContext) repository.UserRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewUserRepo", db)
	ret0, _ := ret[0].(repository.UserRepository)
	return ret0
}

// NewUserRepo indicates an expected call of NewUserRepo.
func (mr *MockRepoManagerMockRecorder) NewUserRepo(db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewUserRepo", reflect.TypeOf((*MockRepoManager)(nil).NewUserRepo), db)
}

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// ActivateUser mocks base method.
func (m *MockUserRepository) ActivateUser(ctx context.Context, userID uint64, currentTime time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateUser", ctx, userID, currentTime)
	ret0, _ := ret[0].(error)
	return ret0
}

// ActivateUser indicates an expected call of ActivateUser.
func (mr *MockUserRepositoryMockRecorder) ActivateUser(ctx, userID, currentTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateUser", reflect.TypeOf((*MockUserRepository)(nil).ActivateUser), ctx, userID, currentTime)
}

// CreateUserProfiles mocks base method.
func (m *MockUserRepository) CreateUserProfiles(ctx context.Context, users domain.Users) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserProfiles", ctx, users)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUserProfiles indicates an expected call of CreateUserProfiles.
func (mr *MockUserRepositoryMockRecorder) CreateUserProfiles(ctx, users any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserProfiles", reflect.TypeOf((*MockUserRepository)(nil).CreateUserProfiles), ctx, users)
}

// CreateUsers mocks base method.
func (m *MockUserRepository) CreateUsers(ctx context.Context, users domain.Users) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUsers", ctx, users)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUsers indicates an expected call of CreateUsers.
func (mr *MockUserRepositoryMockRecorder) CreateUsers(ctx, users any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUsers", reflect.TypeOf((*MockUserRepository)(nil).CreateUsers), ctx, users)
}

// DeactivateUser mocks base method.
func (m *MockUserRepository) DeactivateUser(ctx context.Context, userID uint64, currentTime time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateUser", ctx, userID, currentTime)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateUser indicates an expected call of DeactivateUser.
func (mr *MockUserRepositoryMockRecorder) DeactivateUser(ctx, userID, currentTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateUser", reflect.TypeOf((*MockUserRepository)(nil).DeactivateUser), ctx, userID, currentTime)
}

// DeleteUsers mocks base method.
func (m *MockUserRepository) DeleteUsers(ctx context.Context, userIDs []uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUsers", ctx, userIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUsers indicates an expected call of DeleteUsers.
func (mr *MockUserRepositoryMockRecorder) DeleteUsers(ctx, userIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUsers", reflect.TypeOf((*MockUserRepository)(nil).DeleteUsers), ctx, userIDs)
}

// FetchUsers mocks base method.
func (m *MockUserRepository) FetchUsers(ctx context.Context, filters filter.Filters) (domain.Users, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchUsers", ctx, filters)
	ret0, _ := ret[0].(domain.Users)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchUsers indicates an expected call of FetchUsers.
func (mr *MockUserRepositoryMockRecorder) FetchUsers(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchUsers", reflect.TypeOf((*MockUserRepository)(nil).FetchUsers), ctx, filters)
}

// GetUserByID mocks base method.
func (m *MockUserRepository) GetUserByID(ctx context.Context, userID uint64) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, userID)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserRepositoryMockRecorder) GetUserByID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserRepository)(nil).GetUserByID), ctx, userID)
}

// UpdateUserProfiles mocks base method.
func (m *MockUserRepository) UpdateUserProfiles(ctx context.Context, users domain.Users) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserProfiles", ctx, users)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserProfiles indicates an expected call of UpdateUserProfiles.
func (mr *MockUserRepositoryMockRecorder) UpdateUserProfiles(ctx, users any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserProfiles", reflect.TypeOf((*MockUserRepository)(nil).UpdateUserProfiles), ctx, users)
}

// UpdateUsers mocks base method.
func (m *MockUserRepository) UpdateUsers(ctx context.Context, users domain.Users) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUsers", ctx, users)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUsers indicates an expected call of UpdateUsers.
func (mr *MockUserRepositoryMockRecorder) UpdateUsers(ctx, users any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUsers", reflect.TypeOf((*MockUserRepository)(nil).UpdateUsers), ctx, users)
}

// MockMessageRepository is a mock of MessageRepository interface.
type MockMessageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMessageRepositoryMockRecorder
	isgomock struct{}
}

// MockMessageRepositoryMockRecorder is the mock recorder for MockMessageRepository.
type MockMessageRepositoryMockRecorder struct {
	mock *MockMessageRepository
}

// NewMockMessageRepository creates a new mock instance.
func NewMockMessageRepository(ctrl *gomock.Controller) *MockMessageRepository {
	mock := &MockMessageRepository{ctrl: ctrl}
	mock.recorder = &MockMessageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageRepository) EXPECT() *MockMessageRepositoryMockRecorder {
	return m.recorder
}

// Write mocks base method.
func (m *MockMessageRepository) Write(ctx context.Context, messages domain.Massages) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", ctx, messages)
	ret0, _ := ret[0].(error)
	return ret0
}

// Write indicates an expected call of Write.
func (mr *MockMessageRepositoryMockRecorder) Write(ctx, messages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockMessageRepository)(nil).Write), ctx, messages)
}

// MockAuthRepository is a mock of AuthRepository interface.
type MockAuthRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuthRepositoryMockRecorder
	isgomock struct{}
}

// MockAuthRepositoryMockRecorder is the mock recorder for MockAuthRepository.
type MockAuthRepositoryMockRecorder struct {
	mock *MockAuthRepository
}

// NewMockAuthRepository creates a new mock instance.
func NewMockAuthRepository(ctrl *gomock.Controller) *MockAuthRepository {
	mock := &MockAuthRepository{ctrl: ctrl}
	mock.recorder = &MockAuthRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthRepository) EXPECT() *MockAuthRepositoryMockRecorder {
	return m.recorder
}

// CreateInviteToken mocks base method.
func (m *MockAuthRepository) CreateInviteToken(ctx context.Context, token *domain.InviteToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInviteToken", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateInviteToken indicates an expected call of CreateInviteToken.
func (mr *MockAuthRepositoryMockRecorder) CreateInviteToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInviteToken", reflect.TypeOf((*MockAuthRepository)(nil).CreateInviteToken), ctx, token)
}

// CreateRefreshToken mocks base method.
func (m *MockAuthRepository) CreateRefreshToken(ctx context.Context, token *domain.RefreshToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRefreshToken", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRefreshToken indicates an expected call of CreateRefreshToken.
func (mr *MockAuthRepositoryMockRecorder) CreateRefreshToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRefreshToken", reflect.TypeOf((*MockAuthRepository)(nil).CreateRefreshToken), ctx, token)
}

// CreateUserCredential mocks base method.
func (m *MockAuthRepository) CreateUserCredential(ctx context.Context, cred *domain.UserCredential) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserCredential", ctx, cred)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUserCredential indicates an expected call of CreateUserCredential.
func (mr *MockAuthRepositoryMockRecorder) CreateUserCredential(ctx, cred any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserCredential", reflect.TypeOf((*MockAuthRepository)(nil).CreateUserCredential), ctx, cred)
}

// GetInviteToken mocks base method.
func (m *MockAuthRepository) GetInviteToken(ctx context.Context, token string) (*domain.InviteToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInviteToken", ctx, token)
	ret0, _ := ret[0].(*domain.InviteToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInviteToken indicates an expected call of GetInviteToken.
func (mr *MockAuthRepositoryMockRecorder) GetInviteToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInviteToken", reflect.TypeOf((*MockAuthRepository)(nil).GetInviteToken), ctx, token)
}

// GetRefreshToken mocks base method.
func (m *MockAuthRepository) GetRefreshToken(ctx context.Context, tokenHash string) (*domain.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefreshToken", ctx, tokenHash)
	ret0, _ := ret[0].(*domain.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRefreshToken indicates an expected call of GetRefreshToken.
func (mr *MockAuthRepositoryMockRecorder) GetRefreshToken(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefreshToken", reflect.TypeOf((*MockAuthRepository)(nil).GetRefreshToken), ctx, tokenHash)
}

// GetUserCredentialByEmail mocks base method.
func (m *MockAuthRepository) GetUserCredentialByEmail(ctx context.Context, email string) (*domain.UserCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserCredentialByEmail", ctx, email)
	ret0, _ := ret[0].(*domain.UserCredential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserCredentialByEmail indicates an expected call of GetUserCredentialByEmail.
func (mr *MockAuthRepositoryMockRecorder) GetUserCredentialByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserCredentialByEmail", reflect.TypeOf((*MockAuthRepository)(nil).GetUserCredentialByEmail), ctx, email)
}

// MarkInviteTokenUsed mocks base method.
func (m *MockAuthRepository) MarkInviteTokenUsed(ctx context.Context, token string, usedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkInviteTokenUsed", ctx, token, usedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkInviteTokenUsed indicates an expected call of MarkInviteTokenUsed.
func (mr *MockAuthRepositoryMockRecorder) MarkInviteTokenUsed(ctx, token, usedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkInviteTokenUsed", reflect.TypeOf((*MockAuthRepository)(nil).MarkInviteTokenUsed), ctx, token, usedAt)
}

// RevokeRefreshToken mocks base method.
func (m *MockAuthRepository) RevokeRefreshToken(ctx context.Context, tokenHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeRefreshToken", ctx, tokenHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeRefreshToken indicates an expected call of RevokeRefreshToken.
func (mr *MockAuthRepositoryMockRecorder) RevokeRefreshToken(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeRefreshToken", reflect.TypeOf((*MockAuthRepository)(nil).RevokeRefreshToken), ctx, tokenHash)
}

// UpsertUserCredential mocks base method.
func (m *MockAuthRepository) UpsertUserCredential(ctx context.Context, cred *domain.UserCredential) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertUserCredential", ctx, cred)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertUserCredential indicates an expected call of UpsertUserCredential.
func (mr *MockAuthRepositoryMockRecorder) UpsertUserCredential(ctx, cred any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertUserCredential", reflect.TypeOf((*MockAuthRepository)(nil).UpsertUserCredential), ctx, cred)
}

// MockAcademicYearRepository is a mock of AcademicYearRepository interface.
type MockAcademicYearRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAcademicYearRepositoryMockRecorder
	isgomock struct{}
}

// MockAcademicYearRepositoryMockRecorder is the mock recorder for MockAcademicYearRepository.
type MockAcademicYearRepositoryMockRecorder struct {
	mock *MockAcademicYearRepository
}

// NewMockAcademicYearRepository creates a new mock instance.
func NewMockAcademicYearRepository(ctrl *gomock.Controller) *MockAcademicYearRepository {
	mock := &MockAcademicYearRepository{ctrl: ctrl}
	mock.recorder = &MockAcademicYearRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAcademicYearRepository) EXPECT() *MockAcademicYearRepositoryMockRecorder {
	return m.recorder
}

// DeleteAcademicYear mocks base method.
func (m *MockAcademicYearRepository) DeleteAcademicYear(ctx context.Context, id uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAcademicYear", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAcademicYear indicates an expected call of DeleteAcademicYear.
func (mr *MockAcademicYearRepositoryMockRecorder) DeleteAcademicYear(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAcademicYear", reflect.TypeOf((*MockAcademicYearRepository)(nil).DeleteAcademicYear), ctx, id)
}

// UpsertAcademicYear mocks base method.
func (m *MockAcademicYearRepository) UpsertAcademicYear(ctx context.Context, academicYear *domain.AcademicYear) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertAcademicYear", ctx, academicYear)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertAcademicYear indicates an expected call of UpsertAcademicYear.
func (mr *MockAcademicYearRepositoryMockRecorder) UpsertAcademicYear(ctx, academicYear any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertAcademicYear", reflect.TypeOf((*MockAcademicYearRepository)(nil).UpsertAcademicYear), ctx, academicYear)
}
