// Code generated by MockGen. DO NOT EDIT.
// Source: internal/syllabus/service/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/syllabus/service/interface.go -destination=internal/syllabus/service/mocks/mock.go
//

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	reflect "reflect"

	jwt "github.com/Lapakin/edu-planner/internal/adapter/jwt"
	filter "github.com/Lapakin/edu-planner/internal/app/filter"
	domain "github.com/Lapakin/edu-planner/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockAcademicYearSvc is a mock of AcademicYearSvc interface.
type MockAcademicYearSvc struct {
	ctrl     *gomock.Controller
	recorder *MockAcademicYearSvcMockRecorder
	isgomock struct{}
}

// MockAcademicYearSvcMockRecorder is the mock recorder for MockAcademicYearSvc.
type MockAcademicYearSvcMockRecorder struct {
	mock *MockAcademicYearSvc
}

// NewMockAcademicYearSvc creates a new mock instance.
func NewMockAcademicYearSvc(ctrl *gomock.Controller) *MockAcademicYearSvc {
	mock := &MockAcademicYearSvc{ctrl: ctrl}
	mock.recorder = &MockAcademicYearSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAcademicYearSvc) EXPECT() *MockAcademicYearSvcMockRecorder {
	return m.recorder
}

// ActivateAcademicYear mocks base method.
func (m *MockAcademicYearSvc) ActivateAcademicYear(ctx context.Context, claims *jwt.Claims, id uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateAcademicYear", ctx, claims, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ActivateAcademicYear indicates an expected call of ActivateAcademicYear.
func (mr *MockAcademicYearSvcMockRecorder) ActivateAcademicYear(ctx, claims, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateAcademicYear", reflect.TypeOf((*MockAcademicYearSvc)(nil).ActivateAcademicYear), ctx, claims, id)
}

// CreateAcademicYears mocks base method.
func (m *MockAcademicYearSvc) CreateAcademicYears(ctx context.Context, claims *jwt.Claims, academicYears domain.AcademicYears) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAcademicYears", ctx, claims, academicYears)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAcademicYears indicates an expected call of CreateAcademicYears.
func (mr *MockAcademicYearSvcMockRecorder) CreateAcademicYears(ctx, claims, academicYears any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAcademicYears", reflect.TypeOf((*MockAcademicYearSvc)(nil).CreateAcademicYears), ctx, claims, academicYears)
}

// DeleteAcademicYears mocks base method.
func (m *MockAcademicYearSvc) DeleteAcademicYears(ctx context.Context, claims *jwt.Claims, ids []uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAcademicYears", ctx, claims, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAcademicYears indicates an expected call of DeleteAcademicYears.
func (mr *MockAcademicYearSvcMockRecorder) DeleteAcademicYears(ctx, claims, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAcademicYears", reflect.TypeOf((*MockAcademicYearSvc)(nil).DeleteAcademicYears), ctx, claims, ids)
}

// FetchAcademicYears mocks base method.
func (m *MockAcademicYearSvc) FetchAcademicYears(ctx context.Context, filters filter.Filters) (domain.AcademicYears, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchAcademicYears", ctx, filters)
	ret0, _ := ret[0].(domain.AcademicYears)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchAcademicYears indicates an expected call of FetchAcademicYears.
func (mr *MockAcademicYearSvcMockRecorder) FetchAcademicYears(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchAcademicYears", reflect.TypeOf((*MockAcademicYearSvc)(nil).FetchAcademicYears), ctx, filters)
}

// GetAcademicYearByID mocks base method.
func (m *MockAcademicYearSvc) GetAcademicYearByID(ctx context.Context, id uint64) (*domain.AcademicYear, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAcademicYearByID", ctx, id)
	ret0, _ := ret[0].(*domain.AcademicYear)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAcademicYearByID indicates an expected call of GetAcademicYearByID.
func (mr *MockAcademicYearSvcMockRecorder) GetAcademicYearByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAcademicYearByID", reflect.TypeOf((*MockAcademicYearSvc)(nil).GetAcademicYearByID), ctx, id)
}

// UpdateAcademicYears mocks base method.
func (m *MockAcademicYearSvc) UpdateAcademicYears(ctx context.Context, claims *jwt.Claims, academicYears domain.AcademicYears) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAcademicYears", ctx, claims, academicYears)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAcademicYears indicates an expected call of UpdateAcademicYears.
func (mr *MockAcademicYearSvcMockRecorder) UpdateAcademicYears(ctx, claims, academicYears any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAcademicYears", reflect.TypeOf((*MockAcademicYearSvc)(nil).UpdateAcademicYears), ctx, claims, academicYears)
}

// MockSemesterSvc is a mock of SemesterSvc interface.
type MockSemesterSvc struct {
	ctrl     *gomock.Controller
	recorder *MockSemesterSvcMockRecorder
	isgomock struct{}
}

// MockSemesterSvcMockRecorder is the mock recorder for MockSemesterSvc.
type MockSemesterSvcMockRecorder struct {
	mock *MockSemesterSvc
}

// NewMockSemesterSvc creates a new mock instance.
func NewMockSemesterSvc(ctrl *gomock.Controller) *MockSemesterSvc {
	mock := &MockSemesterSvc{ctrl: ctrl}
	mock.recorder = &MockSemesterSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSemesterSvc) EXPECT() *MockSemesterSvcMockRecorder {
	return m.recorder
}

// CreateSemesters mocks base method.
func (m *MockSemesterSvc) CreateSemesters(ctx context.Context, claims *jwt.Claims, semesters domain.Semesters) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSemesters", ctx, claims, semesters)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSemesters indicates an expected call of CreateSemesters.
func (mr *MockSemesterSvcMockRecorder) CreateSemesters(ctx, claims, semesters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSemesters", reflect.TypeOf((*MockSemesterSvc)(nil).CreateSemesters), ctx, claims, semesters)
}

// DeleteSemesters mocks base method.
func (m *MockSemesterSvc) DeleteSemesters(ctx context.Context, claims *jwt.Claims, ids []uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSemesters", ctx, claims, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSemesters indicates an expected call of DeleteSemesters.
func (mr *MockSemesterSvcMockRecorder) DeleteSemesters(ctx, claims, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSemesters", reflect.TypeOf((*MockSemesterSvc)(nil).DeleteSemesters), ctx, claims, ids)
}

// FetchSemesters mocks base method.
func (m *MockSemesterSvc) FetchSemesters(ctx context.Context, filters filter.Filters) (domain.Semesters, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchSemesters", ctx, filters)
	ret0, _ := ret[0].(domain.Semesters)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchSemesters indicates an expected call of FetchSemesters.
func (mr *MockSemesterSvcMockRecorder) FetchSemesters(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchSemesters", reflect.TypeOf((*MockSemesterSvc)(nil).FetchSemesters), ctx, filters)
}

// GetSemesterByID mocks base method.
func (m *MockSemesterSvc) GetSemesterByID(ctx context.Context, id uint64) (*domain.Semester, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSemesterByID", ctx, id)
	ret0, _ := ret[0].(*domain.Semester)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSemesterByID indicates an expected call of GetSemesterByID.
func (mr *MockSemesterSvcMockRecorder) GetSemesterByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSemesterByID", reflect.TypeOf((*MockSemesterSvc)(nil).GetSemesterByID), ctx, id)
}

// UpdateSemesters mocks base method.
func (m *MockSemesterSvc) UpdateSemesters(ctx context.Context, claims *jwt.Claims, semesters domain.Semesters) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSemesters", ctx, claims, semesters)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSemesters indicates an expected call of UpdateSemesters.
func (mr *MockSemesterSvcMockRecorder) UpdateSemesters(ctx, claims, semesters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSemesters", reflect.TypeOf((*MockSemesterSvc)(nil).UpdateSemesters), ctx, claims, semesters)
}

// MockDepartmentSvc is a mock of DepartmentSvc interface.
type MockDepartmentSvc struct {
	ctrl     *gomock.Controller
	recorder *MockDepartmentSvcMockRecorder
	isgomock struct{}
}

// MockDepartmentSvcMockRecorder is the mock recorder for MockDepartmentSvc.
type MockDepartmentSvcMockRecorder struct {
	mock *MockDepartmentSvc
}

// NewMockDepartmentSvc creates a new mock instance.
func NewMockDepartmentSvc(ctrl *gomock.Controller) *MockDepartmentSvc {
	mock := &MockDepartmentSvc{ctrl: ctrl}
	mock.recorder = &MockDepartmentSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDepartmentSvc) EXPECT() *MockDepartmentSvcMockRecorder {
	return m.recorder
}

// CreateDepartments mocks base method.
func (m *MockDepartmentSvc) CreateDepartments(ctx context.Context, claims *jwt.Claims, departments domain.Departments) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDepartments", ctx, claims, departments)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDepartments indicates an expected call of CreateDepartments.
func (mr *MockDepartmentSvcMockRecorder) CreateDepartments(ctx, claims, departments any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDepartments", reflect.TypeOf((*MockDepartmentSvc)(nil).CreateDepartments), ctx, claims, departments)
}

// DeleteDepartments mocks base method.
func (m *MockDepartmentSvc) DeleteDepartments(ctx context.Context, claims *jwt.Claims, ids []uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDepartments", ctx, claims, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDepartments indicates an expected call of DeleteDepartments.
func (mr *MockDepartmentSvcMockRecorder) DeleteDepartments(ctx, claims, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDepartments", reflect.TypeOf((*MockDepartmentSvc)(nil).DeleteDepartments), ctx, claims, ids)
}

// FetchDepartments mocks base method.
func (m *MockDepartmentSvc) FetchDepartments(ctx context.Context, filters filter.Filters) (domain.Departments, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchDepartments", ctx, filters)
	ret0, _ := ret[0].(domain.Departments)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchDepartments indicates an expected call of FetchDepartments.
func (mr *MockDepartmentSvcMockRecorder) FetchDepartments(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchDepartments", reflect.TypeOf((*MockDepartmentSvc)(nil).FetchDepartments), ctx, filters)
}

// GetDepartmentByID mocks base method.
func (m *MockDepartmentSvc) GetDepartmentByID(ctx context.Context, id uint64) (*domain.Department, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDepartmentByID", ctx, id)
	ret0, _ := ret[0].(*domain.Department)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDepartmentByID indicates an expected call of GetDepartmentByID.
func (mr *MockDepartmentSvcMockRecorder) GetDepartmentByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDepartmentByID", reflect.TypeOf((*MockDepartmentSvc)(nil).GetDepartmentByID), ctx, id)
}

// UpdateDepartments mocks base method.
func (m *MockDepartmentSvc) UpdateDepartments(ctx context.Context, claims *jwt.Claims, departments domain.Departments) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDepartments", ctx, claims, departments)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDepartments indicates an expected call of UpdateDepartments.
func (mr *MockDepartmentSvcMockRecorder) UpdateDepartments(ctx, claims, departments any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDepartments", reflect.TypeOf((*MockDepartmentSvc)(nil).UpdateDepartments), ctx, claims, departments)
}

// MockRoomSvc is a mock of RoomSvc interface.
type MockRoomSvc struct {
	ctrl     *gomock.Controller
	recorder *MockRoomSvcMockRecorder
	isgomock struct{}
}

// MockRoomSvcMockRecorder is the mock recorder for MockRoomSvc.
type MockRoomSvcMockRecorder struct {
	mock *MockRoomSvc
}

// NewMockRoomSvc creates a new mock instance.
func NewMockRoomSvc(ctrl *gomock.Controller) *MockRoomSvc {
	mock := &MockRoomSvc{ctrl: ctrl}
	mock.recorder = &MockRoomSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomSvc) EXPECT() *MockRoomSvcMockRecorder {
	return m.recorder
}

// CreateRooms mocks base method.
func (m *MockRoomSvc) CreateRooms(ctx context.Context, claims *jwt.Claims, rooms domain.Rooms) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRooms", ctx, claims, rooms)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRooms indicates an expected call of CreateRooms.
func (mr *MockRoomSvcMockRecorder) CreateRooms(ctx, claims, rooms any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRooms", reflect.TypeOf((*MockRoomSvc)(nil).CreateRooms), ctx, claims, rooms)
}

// DeleteRooms mocks base method.
func (m *MockRoomSvc) DeleteRooms(ctx context.Context, claims *jwt.Claims, ids []uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRooms", ctx, claims, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRooms indicates an expected call of DeleteRooms.
func (mr *MockRoomSvcMockRecorder) DeleteRooms(ctx, claims, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRooms", reflect.TypeOf((*MockRoomSvc)(nil).DeleteRooms), ctx, claims, ids)
}

// FetchRooms mocks base method.
func (m *MockRoomSvc) FetchRooms(ctx context.Context, filters filter.Filters) (domain.Rooms, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchRooms", ctx, filters)
	ret0, _ := ret[0].(domain.Rooms)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchRooms indicates an expected call of FetchRooms.
func (mr *MockRoomSvcMockRecorder) FetchRooms(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchRooms", reflect.TypeOf((*MockRoomSvc)(nil).FetchRooms), ctx, filters)
}

// GetRoomByID mocks base method.
func (m *MockRoomSvc) GetRoomByID(ctx context.Context, id uint64) (*domain.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoomByID", ctx, id)
	ret0, _ := ret[0].(*domain.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoomByID indicates an expected call of GetRoomByID.
func (mr *MockRoomSvcMockRecorder) GetRoomByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoomByID", reflect.TypeOf((*MockRoomSvc)(nil).GetRoomByID), ctx, id)
}

// UpdateRooms mocks base method.
func (m *MockRoomSvc) UpdateRooms(ctx context.Context, claims *jwt.Claims, rooms domain.Rooms) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRooms", ctx, claims, rooms)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRooms indicates an expected call of UpdateRooms.
func (mr *MockRoomSvcMockRecorder) UpdateRooms(ctx, claims, rooms any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRooms", reflect.TypeOf((*MockRoomSvc)(nil).UpdateRooms), ctx, claims, rooms)
}

// MockSpecialtySvc is a mock of SpecialtySvc interface.
type MockSpecialtySvc struct {
	ctrl     *gomock.Controller
	recorder *MockSpecialtySvcMockRecorder
	isgomock struct{}
}

// MockSpecialtySvcMockRecorder is the mock recorder for MockSpecialtySvc.
type MockSpecialtySvcMockRecorder struct {
	mock *MockSpecialtySvc
}

// NewMockSpecialtySvc creates a new mock instance.
func NewMockSpecialtySvc(ctrl *gomock.Controller) *MockSpecialtySvc {
	mock := &MockSpecialtySvc{ctrl: ctrl}
	mock.recorder = &MockSpecialtySvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpecialtySvc) EXPECT() *MockSpecialtySvcMockRecorder {
	return m.recorder
}

// CreateSpecialties mocks base method.
func (m *MockSpecialtySvc) CreateSpecialties(ctx context.Context, claims *jwt.Claims, specialities domain.Specialties) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSpecialties", ctx, claims, specialities)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSpecialties indicates an expected call of CreateSpecialties.
func (mr *MockSpecialtySvcMockRecorder) CreateSpecialties(ctx, claims, specialities any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSpecialties", reflect.TypeOf((*MockSpecialtySvc)(nil).CreateSpecialties), ctx, claims, specialities)
}

// DeleteSpecialties mocks base method.
func (m *MockSpecialtySvc) DeleteSpecialties(ctx context.Context, claims *jwt.Claims, ids []uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSpecialties", ctx, claims, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSpecialties indicates an expected call of DeleteSpecialties.
func (mr *MockSpecialtySvcMockRecorder) DeleteSpecialties(ctx, claims, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSpecialties", reflect.TypeOf((*MockSpecialtySvc)(nil).DeleteSpecialties), ctx, claims, ids)
}

// FetchSpecialties mocks base method.
func (m *MockSpecialtySvc) FetchSpecialties(ctx context.Context, filters filter.Filters) (domain.Specialties, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchSpecialties", ctx, filters)
	ret0, _ := ret[0].(domain.Specialties)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchSpecialties indicates an expected call of FetchSpecialties.
func (mr *MockSpecialtySvcMockRecorder) FetchSpecialties(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchSpecialties", reflect.TypeOf((*MockSpecialtySvc)(nil).FetchSpecialties), ctx, filters)
}

// GetSpecialtyByID mocks base method.
func (m *MockSpecialtySvc) GetSpecialtyByID(ctx context.Context, id uint64) (*domain.Specialty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSpecialtyByID", ctx, id)
	ret0, _ := ret[0].(*domain.Specialty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSpecialtyByID indicates an expected call of GetSpecialtyByID.
func (mr *MockSpecialtySvcMockRecorder) GetSpecialtyByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSpecialtyByID", reflect.TypeOf((*MockSpecialtySvc)(nil).GetSpecialtyByID), ctx, id)
}

// UpdateSpecialties mocks base method.
func (m *MockSpecialtySvc) UpdateSpecialties(ctx context.Context, claims *jwt.Claims, specialities domain.Specialties) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSpecialties", ctx, claims, specialities)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSpecialties indicates an expected call of UpdateSpecialties.
func (mr *MockSpecialtySvcMockRecorder) UpdateSpecialties(ctx, claims, specialities any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSpecialties", reflect.TypeOf((*MockSpecialtySvc)(nil).UpdateSpecialties), ctx, claims, specialities)
}

// MockCycleCommitteeSvc is a mock of CycleCommitteeSvc interface.
type MockCycleCommitteeSvc struct {
	ctrl     *gomock.Controller
	recorder *MockCycleCommitteeSvcMockRecorder
	isgomock struct{}
}

// MockCycleCommitteeSvcMockRecorder is the mock recorder for MockCycleCommitteeSvc.
type MockCycleCommitteeSvcMockRecorder struct {
	mock *MockCycleCommitteeSvc
}

// NewMockCycleCommitteeSvc creates a new mock instance.
func NewMockCycleCommitteeSvc(ctrl *gomock.Controller) *MockCycleCommitteeSvc {
	mock := &MockCycleCommitteeSvc{ctrl: ctrl}
	mock.recorder = &MockCycleCommitteeSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCycleCommitteeSvc) EXPECT() *MockCycleCommitteeSvcMockRecorder {
	return m.recorder
}

// CreateCycleCommittees mocks base method.
func (m *MockCycleCommitteeSvc) CreateCycleCommittees(ctx context.Context, claims *jwt.Claims, cycleCommittees domain.CycleCommittees) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCycleCommittees", ctx, claims, cycleCommittees)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCycleCommittees indicates an expected call of CreateCycleCommittees.
func (mr *MockCycleCommitteeSvcMockRecorder) CreateCycleCommittees(ctx, claims, cycleCommittees any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCycleCommittees", reflect.TypeOf((*MockCycleCommitteeSvc)(nil).CreateCycleCommittees), ctx, claims, cycleCommittees)
}

// DeleteCycleCommittees mocks base method.
func (m *MockCycleCommitteeSvc) DeleteCycleCommittees(ctx context.Context, claims *jwt.Claims, ids []uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCycleCommittees", ctx, claims, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCycleCommittees indicates an expected call of DeleteCycleCommittees.
func (mr *MockCycleCommitteeSvcMockRecorder) DeleteCycleCommittees(ctx, claims, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCycleCommittees", reflect.TypeOf((*MockCycleCommitteeSvc)(nil).DeleteCycleCommittees), ctx, claims, ids)
}

// FetchCycleCommittees mocks base method.
func (m *MockCycleCommitteeSvc) FetchCycleCommittees(ctx context.Context, filters filter.Filters) (domain.CycleCommittees, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchCycleCommittees", ctx, filters)
	ret0, _ := ret[0].(domain.CycleCommittees)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchCycleCommittees indicates an expected call of FetchCycleCommittees.
func (mr *MockCycleCommitteeSvcMockRecorder) FetchCycleCommittees(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchCycleCommittees", reflect.TypeOf((*MockCycleCommitteeSvc)(nil).FetchCycleCommittees), ctx, filters)
}

// GetCycleCommitteeByID mocks base method.
func (m *MockCycleCommitteeSvc) GetCycleCommitteeByID(ctx context.Context, id uint64) (*domain.CycleCommittee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCycleCommitteeByID", ctx, id)
	ret0, _ := ret[0].(*domain.CycleCommittee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCycleCommitteeByID indicates an expected call of GetCycleCommitteeByID.
func (mr *MockCycleCommitteeSvcMockRecorder) GetCycleCommitteeByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCycleCommitteeByID", reflect.TypeOf((*MockCycleCommitteeSvc)(nil).GetCycleCommitteeByID), ctx, id)
}

// UpdateCycleCommittees mocks base method.
func (m *MockCycleCommitteeSvc) UpdateCycleCommittees(ctx context.Context, claims *jwt.Claims, cycleCommittees domain.CycleCommittees) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCycleCommittees", ctx, claims, cycleCommittees)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCycleCommittees indicates an expected call of UpdateCycleCommittees.
func (mr *MockCycleCommitteeSvcMockRecorder) UpdateCycleCommittees(ctx, claims, cycleCommittees any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCycleCommittees", reflect.TypeOf((*MockCycleCommitteeSvc)(nil).UpdateCycleCommittees), ctx, claims, cycleCommittees)
}

// MockTeacherSvc is a mock of TeacherSvc interface.
type MockTeacherSvc struct {
	ctrl     *gomock.Controller
	recorder *MockTeacherSvcMockRecorder
	isgomock struct{}
}

// MockTeacherSvcMockRecorder is the mock recorder for MockTeacherSvc.
type MockTeacherSvcMockRecorder struct {
	mock *MockTeacherSvc
}

// NewMockTeacherSvc creates a new mock instance.
func NewMockTeacherSvc(ctrl *gomock.Controller) *MockTeacherSvc {
	mock := &MockTeacherSvc{ctrl: ctrl}
	mock.recorder = &MockTeacherSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeacherSvc) EXPECT() *MockTeacherSvcMockRecorder {
	return m.recorder
}

// CreateTeachers mocks base method.
func (m *MockTeacherSvc) CreateTeachers(ctx context.Context, claims *jwt.Claims, teachers domain.Teachers) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTeachers", ctx, claims, teachers)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTeachers indicates an expected call of CreateTeachers.
func (mr *MockTeacherSvcMockRecorder) CreateTeachers(ctx, claims, teachers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTeachers", reflect.TypeOf((*MockTeacherSvc)(nil).CreateTeachers), ctx, claims, teachers)
}

// DeleteTeachers mocks base method.
func (m *MockTeacherSvc) DeleteTeachers(ctx context.Context, claims *jwt.Claims, ids []uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTeachers", ctx, claims, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTeachers indicates an expected call of DeleteTeachers.
func (mr *MockTeacherSvcMockRecorder) DeleteTeachers(ctx, claims, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTeachers", reflect.TypeOf((*MockTeacherSvc)(nil).DeleteTeachers), ctx, claims, ids)
}

// FetchTeachers mocks base method.
func (m *MockTeacherSvc) FetchTeachers(ctx context.Context, filters filter.Filters) (domain.Teachers, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchTeachers", ctx, filters)
	ret0, _ := ret[0].(domain.Teachers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchTeachers indicates an expected call of FetchTeachers.
func (mr *MockTeacherSvcMockRecorder) FetchTeachers(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchTeachers", reflect.TypeOf((*MockTeacherSvc)(nil).FetchTeachers), ctx, filters)
}

// GetTeacherByID mocks base method.
func (m *MockTeacherSvc) GetTeacherByID(ctx context.Context, id uint64) (*domain.Teacher, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeacherByID", ctx, id)
	ret0, _ := ret[0].(*domain.Teacher)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeacherByID indicates an expected call of GetTeacherByID.
func (mr *MockTeacherSvcMockRecorder) GetTeacherByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeacherByID", reflect.TypeOf((*MockTeacherSvc)(nil).GetTeacherByID), ctx, id)
}

// UpdateTeachers mocks base method.
func (m *MockTeacherSvc) UpdateTeachers(ctx context.Context, claims *jwt.Claims, teachers domain.Teachers) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTeachers", ctx, claims, teachers)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTeachers indicates an expected call of UpdateTeachers.
func (mr *MockTeacherSvcMockRecorder) UpdateTeachers(ctx, claims, teachers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTeachers", reflect.TypeOf((*MockTeacherSvc)(nil).UpdateTeachers), ctx, claims, teachers)
}

// MockDisciplineSvc is a mock of DisciplineSvc interface.
type MockDisciplineSvc struct {
	ctrl     *gomock.Controller
	recorder *MockDisciplineSvcMockRecorder
	isgomock struct{}
}

// MockDisciplineSvcMockRecorder is the mock recorder for MockDisciplineSvc.
type MockDisciplineSvcMockRecorder struct {
	mock *MockDisciplineSvc
}

// NewMockDisciplineSvc creates a new mock instance.
func NewMockDisciplineSvc(ctrl *gomock.Controller) *MockDisciplineSvc {
	mock := &MockDisciplineSvc{ctrl: ctrl}
	mock.recorder = &MockDisciplineSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDisciplineSvc) EXPECT() *MockDisciplineSvcMockRecorder {
	return m.recorder
}

// CreateDisciplines mocks base method.
func (m *MockDisciplineSvc) CreateDisciplines(ctx context.Context, claims *jwt.Claims, disciplines domain.Disciplines) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDisciplines", ctx, claims, disciplines)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDisciplines indicates an expected call of CreateDisciplines.
func (mr *MockDisciplineSvcMockRecorder) CreateDisciplines(ctx, claims, disciplines any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDisciplines", reflect.TypeOf((*MockDisciplineSvc)(nil).CreateDisciplines), ctx, claims, disciplines)
}

// DeleteDisciplines mocks base method.
func (m *MockDisciplineSvc) DeleteDisciplines(ctx context.Context, claims *jwt.Claims, ids []uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDisciplines", ctx, claims, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDisciplines indicates an expected call of DeleteDisciplines.
func (mr *MockDisciplineSvcMockRecorder) DeleteDisciplines(ctx, claims, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDisciplines", reflect.TypeOf((*MockDisciplineSvc)(nil).DeleteDisciplines), ctx, claims, ids)
}

// FetchDisciplines mocks base method.
func (m *MockDisciplineSvc) FetchDisciplines(ctx context.Context, filters filter.Filters) (domain.Disciplines, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchDisciplines", ctx, filters)
	ret0, _ := ret[0].(domain.Disciplines)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchDisciplines indicates an expected call of FetchDisciplines.
func (mr *MockDisciplineSvcMockRecorder) FetchDisciplines(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchDisciplines", reflect.TypeOf((*MockDisciplineSvc)(nil).FetchDisciplines), ctx, filters)
}

// GetDisciplineByID mocks base method.
func (m *MockDisciplineSvc) GetDisciplineByID(ctx context.Context, id uint64) (*domain.Discipline, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDisciplineByID", ctx, id)
	ret0, _ := ret[0].(*domain.Discipline)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDisciplineByID indicates an expected call of GetDisciplineByID.
func (mr *MockDisciplineSvcMockRecorder) GetDisciplineByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDisciplineByID", reflect.TypeOf((*MockDisciplineSvc)(nil).GetDisciplineByID), ctx, id)
}

// UpdateDisciplines mocks base method.
func (m *MockDisciplineSvc) UpdateDisciplines(ctx context.Context, claims *jwt.Claims, disciplines domain.Disciplines) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDisciplines", ctx, claims, disciplines)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDisciplines indicates an expected call of UpdateDisciplines.
func (mr *MockDisciplineSvcMockRecorder) UpdateDisciplines(ctx, claims, disciplines any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDisciplines", reflect.TypeOf((*MockDisciplineSvc)(nil).UpdateDisciplines), ctx, claims, disciplines)
}

// MockGroupSvc is a mock of GroupSvc interface.
type MockGroupSvc struct {
	ctrl     *gomock.Controller
	recorder *MockGroupSvcMockRecorder
	isgomock struct{}
}

// MockGroupSvcMockRecorder is the mock recorder for MockGroupSvc.
type MockGroupSvcMockRecorder struct {
	mock *MockGroupSvc
}

// NewMockGroupSvc creates a new mock instance.
func NewMockGroupSvc(ctrl *gomock.Controller) *MockGroupSvc {
	mock := &MockGroupSvc{ctrl: ctrl}
	mock.recorder = &MockGroupSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGroupSvc) EXPECT() *MockGroupSvcMockRecorder {
	return m.recorder
}

// CreateGroupSemesters mocks base method.
func (m *MockGroupSvc) CreateGroupSemesters(ctx context.Context, claims *jwt.Claims, groupSemesters domain.GroupSemesters) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGroupSemesters", ctx, claims, groupSemesters)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateGroupSemesters indicates an expected call of CreateGroupSemesters.
func (mr *MockGroupSvcMockRecorder) CreateGroupSemesters(ctx, claims, groupSemesters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGroupSemesters", reflect.TypeOf((*MockGroupSvc)(nil).CreateGroupSemesters), ctx, claims, groupSemesters)
}

// CreateGroups mocks base method.
func (m *MockGroupSvc) CreateGroups(ctx context.Context, claims *jwt.Claims, groups domain.Groups) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGroups", ctx, claims, groups)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateGroups indicates an expected call of CreateGroups.
func (mr *MockGroupSvcMockRecorder) CreateGroups(ctx, claims, groups any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGroups", reflect.TypeOf((*MockGroupSvc)(nil).CreateGroups), ctx, claims, groups)
}

// DeleteGroupSemesters mocks base method.
func (m *MockGroupSvc) DeleteGroupSemesters(ctx context.Context, claims *jwt.Claims, ids []uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGroupSemesters", ctx, claims, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGroupSemesters indicates an expected call of DeleteGroupSemesters.
func (mr *MockGroupSvcMockRecorder) DeleteGroupSemesters(ctx, claims, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGroupSemesters", reflect.TypeOf((*MockGroupSvc)(nil).DeleteGroupSemesters), ctx, claims, ids)
}

// DeleteGroups mocks base method.
func (m *MockGroupSvc) DeleteGroups(ctx context.Context, claims *jwt.Claims, ids []uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGroups", ctx, claims, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGroups indicates an expected call of DeleteGroups.
func (mr *MockGroupSvcMockRecorder) DeleteGroups(ctx, claims, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGroups", reflect.TypeOf((*MockGroupSvc)(nil).DeleteGroups), ctx, claims, ids)
}

// FetchGroupSemesters mocks base method.
func (m *MockGroupSvc) FetchGroupSemesters(ctx context.Context, filters filter.Filters) (domain.GroupSemesters, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchGroupSemesters", ctx, filters)
	ret0, _ := ret[0].(domain.GroupSemesters)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchGroupSemesters indicates an expected call of FetchGroupSemesters.
func (mr *MockGroupSvcMockRecorder) FetchGroupSemesters(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchGroupSemesters", reflect.TypeOf((*MockGroupSvc)(nil).FetchGroupSemesters), ctx, filters)
}

// FetchGroups mocks base method.
func (m *MockGroupSvc) FetchGroups(ctx context.Context, filters filter.Filters) (domain.Groups, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchGroups", ctx, filters)
	ret0, _ := ret[0].(domain.Groups)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchGroups indicates an expected call of FetchGroups.
func (mr *MockGroupSvcMockRecorder) FetchGroups(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchGroups", reflect.TypeOf((*MockGroupSvc)(nil).FetchGroups), ctx, filters)
}

// GetGroupByID mocks base method.
func (m *MockGroupSvc) GetGroupByID(ctx context.Context, id uint64) (*domain.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupByID", ctx, id)
	ret0, _ := ret[0].(*domain.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupByID indicates an expected call of GetGroupByID.
func (mr *MockGroupSvcMockRecorder) GetGroupByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupByID", reflect.TypeOf((*MockGroupSvc)(nil).GetGroupByID), ctx, id)
}

// GetGroupSemesterByID mocks base method.
func (m *MockGroupSvc) GetGroupSemesterByID(ctx context.Context, id uint64) (*domain.GroupSemester, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupSemesterByID", ctx, id)
	ret0, _ := ret[0].(*domain.GroupSemester)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupSemesterByID indicates an expected call of GetGroupSemesterByID.
func (mr *MockGroupSvcMockRecorder) GetGroupSemesterByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupSemesterByID", reflect.TypeOf((*MockGroupSvc)(nil).GetGroupSemesterByID), ctx, id)
}

// UpdateGroupSemesters mocks base method.
func (m *MockGroupSvc) UpdateGroupSemesters(ctx context.Context, claims *jwt.Claims, groupSemesters domain.GroupSemesters) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGroupSemesters", ctx, claims, groupSemesters)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateGroupSemesters indicates an expected call of UpdateGroupSemesters.
func (mr *MockGroupSvcMockRecorder) UpdateGroupSemesters(ctx, claims, groupSemesters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGroupSemesters", reflect.TypeOf((*MockGroupSvc)(nil).UpdateGroupSemesters), ctx, claims, groupSemesters)
}

// UpdateGroups mocks base method.
func (m *MockGroupSvc) UpdateGroups(ctx context.Context, claims *jwt.Claims, groups domain.Groups) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGroups", ctx, claims, groups)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateGroups indicates an expected call of UpdateGroups.
func (mr *MockGroupSvcMockRecorder) UpdateGroups(ctx, claims, groups any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGroups", reflect.TypeOf((*MockGroupSvc)(nil).UpdateGroups), ctx, claims, groups)
}

// MockStudyPlanSvc is a mock of StudyPlanSvc interface.
type MockStudyPlanSvc struct {
	ctrl     *gomock.Controller
	recorder *MockStudyPlanSvcMockRecorder
	isgomock struct{}
}

// MockStudyPlanSvcMockRecorder is the mock recorder for MockStudyPlanSvc.
type MockStudyPlanSvcMockRecorder struct {
	mock *MockStudyPlanSvc
}

// NewMockStudyPlanSvc creates a new mock instance.
func NewMockStudyPlanSvc(ctrl *gomock.Controller) *MockStudyPlanSvc {
	mock := &MockStudyPlanSvc{ctrl: ctrl}
	mock.recorder = &MockStudyPlanSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStudyPlanSvc) EXPECT() *MockStudyPlanSvcMockRecorder {
	return m.recorder
}

// CreateStudyPlans mocks base method.
func (m *MockStudyPlanSvc) CreateStudyPlans(ctx context.Context, claims *jwt.Claims, studyPlans domain.StudyPlans) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStudyPlans", ctx, claims, studyPlans)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateStudyPlans indicates an expected call of CreateStudyPlans.
func (mr *MockStudyPlanSvcMockRecorder) CreateStudyPlans(ctx, claims, studyPlans any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStudyPlans", reflect.TypeOf((*MockStudyPlanSvc)(nil).CreateStudyPlans), ctx, claims, studyPlans)
}

// DeleteStudyPlans mocks base method.
func (m *MockStudyPlanSvc) DeleteStudyPlans(ctx context.Context, claims *jwt.Claims, ids []uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStudyPlans", ctx, claims, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteStudyPlans indicates an expected call of DeleteStudyPlans.
func (mr *MockStudyPlanSvcMockRecorder) DeleteStudyPlans(ctx, claims, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStudyPlans", reflect.TypeOf((*MockStudyPlanSvc)(nil).DeleteStudyPlans), ctx, claims, ids)
}

// FetchStudyPlans mocks base method.
func (m *MockStudyPlanSvc) FetchStudyPlans(ctx context.Context, filters filter.Filters) (domain.StudyPlans, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchStudyPlans", ctx, filters)
	ret0, _ := ret[0].(domain.StudyPlans)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchStudyPlans indicates an expected call of FetchStudyPlans.
func (mr *MockStudyPlanSvcMockRecorder) FetchStudyPlans(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchStudyPlans", reflect.TypeOf((*MockStudyPlanSvc)(nil).FetchStudyPlans), ctx, filters)
}

// GetStudyPlanByID mocks base method.
func (m *MockStudyPlanSvc) GetStudyPlanByID(ctx context.Context, id uint64) (*domain.StudyPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudyPlanByID", ctx, id)
	ret0, _ := ret[0].(*domain.StudyPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudyPlanByID indicates an expected call of GetStudyPlanByID.
func (mr *MockStudyPlanSvcMockRecorder) GetStudyPlanByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudyPlanByID", reflect.TypeOf((*MockStudyPlanSvc)(nil).GetStudyPlanByID), ctx, id)
}

// UpdateStudyPlans mocks base method.
func (m *MockStudyPlanSvc) UpdateStudyPlans(ctx context.Context, claims *jwt.Claims, studyPlans domain.StudyPlans) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStudyPlans", ctx, claims, studyPlans)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStudyPlans indicates an expected call of UpdateStudyPlans.
func (mr *MockStudyPlanSvcMockRecorder) UpdateStudyPlans(ctx, claims, studyPlans any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStudyPlans", reflect.TypeOf((*MockStudyPlanSvc)(nil).UpdateStudyPlans), ctx, claims, studyPlans)
}

// MockWorkloadDistributionSvc is a mock of WorkloadDistributionSvc interface.
type MockWorkloadDistributionSvc struct {
	ctrl     *gomock.Controller
	recorder *MockWorkloadDistributionSvcMockRecorder
	isgomock struct{}
}

// MockWorkloadDistributionSvcMockRecorder is the mock recorder for MockWorkloadDistributionSvc.
type MockWorkloadDistributionSvcMockRecorder struct {
	mock *MockWorkloadDistributionSvc
}

// NewMockWorkloadDistributionSvc creates a new mock instance.
func NewMockWorkloadDistributionSvc(ctrl *gomock.Controller) *MockWorkloadDistributionSvc {
	mock := &MockWorkloadDistributionSvc{ctrl: ctrl}
	mock.recorder = &MockWorkloadDistributionSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkloadDistributionSvc) EXPECT() *MockWorkloadDistributionSvcMockRecorder {
	return m.recorder
}

// CreateWorkloadDistributions mocks base method.
func (m *MockWorkloadDistributionSvc) CreateWorkloadDistributions(ctx context.Context, claims *jwt.Claims, distributions domain.WorkloadDistributions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWorkloadDistributions", ctx, claims, distributions)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWorkloadDistributions indicates an expected call of CreateWorkloadDistributions.
func (mr *MockWorkloadDistributionSvcMockRecorder) CreateWorkloadDistributions(ctx, claims, distributions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWorkloadDistributions", reflect.TypeOf((*MockWorkloadDistributionSvc)(nil).CreateWorkloadDistributions), ctx, claims, distributions)
}

// DeleteWorkloadDistributions mocks base method.
func (m *MockWorkloadDistributionSvc) DeleteWorkloadDistributions(ctx context.Context, claims *jwt.Claims, ids []uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWorkloadDistributions", ctx, claims, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWorkloadDistributions indicates an expected call of DeleteWorkloadDistributions.
func (mr *MockWorkloadDistributionSvcMockRecorder) DeleteWorkloadDistributions(ctx, claims, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWorkloadDistributions", reflect.TypeOf((*MockWorkloadDistributionSvc)(nil).DeleteWorkloadDistributions), ctx, claims, ids)
}

// FetchWorkloadDistributions mocks base method.
func (m *MockWorkloadDistributionSvc) FetchWorkloadDistributions(ctx context.Context, filters filter.Filters) (domain.WorkloadDistributions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchWorkloadDistributions", ctx, filters)
	ret0, _ := ret[0].(domain.WorkloadDistributions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchWorkloadDistributions indicates an expected call of FetchWorkloadDistributions.
func (mr *MockWorkloadDistributionSvcMockRecorder) FetchWorkloadDistributions(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchWorkloadDistributions", reflect.TypeOf((*MockWorkloadDistributionSvc)(nil).FetchWorkloadDistributions), ctx, filters)
}

// GetWorkloadDistributionByID mocks base method.
func (m *MockWorkloadDistributionSvc) GetWorkloadDistributionByID(ctx context.Context, id uint64) (*domain.WorkloadDistribution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkloadDistributionByID", ctx, id)
	ret0, _ := ret[0].(*domain.WorkloadDistribution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkloadDistributionByID indicates an expected call of GetWorkloadDistributionByID.
func (mr *MockWorkloadDistributionSvcMockRecorder) GetWorkloadDistributionByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkloadDistributionByID", reflect.TypeOf((*MockWorkloadDistributionSvc)(nil).GetWorkloadDistributionByID), ctx, id)
}

// UpdateWorkloadDistributions mocks base method.
func (m *MockWorkloadDistributionSvc) UpdateWorkloadDistributions(ctx context.Context, claims *jwt.Claims, distributions domain.WorkloadDistributions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWorkloadDistributions", ctx, claims, distributions)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWorkloadDistributions indicates an expected call of UpdateWorkloadDistributions.
func (mr *MockWorkloadDistributionSvcMockRecorder) UpdateWorkloadDistributions(ctx, claims, distributions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWorkloadDistributions", reflect.TypeOf((*MockWorkloadDistributionSvc)(nil).UpdateWorkloadDistributions), ctx, claims, distributions)
}

// MockWorkloadAssignmentSvc is a mock of WorkloadAssignmentSvc interface.
type MockWorkloadAssignmentSvc struct {
	ctrl     *gomock.Controller
	recorder *MockWorkloadAssignmentSvcMockRecorder
	isgomock struct{}
}

// MockWorkloadAssignmentSvcMockRecorder is the mock recorder for MockWorkloadAssignmentSvc.
type MockWorkloadAssignmentSvcMockRecorder struct {
	mock *MockWorkloadAssignmentSvc
}

// NewMockWorkloadAssignmentSvc creates a new mock instance.
func NewMockWorkloadAssignmentSvc(ctrl *gomock.Controller) *MockWorkloadAssignmentSvc {
	mock := &MockWorkloadAssignmentSvc{ctrl: ctrl}
	mock.recorder = &MockWorkloadAssignmentSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkloadAssignmentSvc) EXPECT() *MockWorkloadAssignmentSvcMockRecorder {
	return m.recorder
}

// CreateWorkloadAssignments mocks base method.
func (m *MockWorkloadAssignmentSvc) CreateWorkloadAssignments(ctx context.Context, claims *jwt.Claims, assignments domain.WorkloadAssignments) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWorkloadAssignments", ctx, claims, assignments)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWorkloadAssignments indicates an expected call of CreateWorkloadAssignments.
func (mr *MockWorkloadAssignmentSvcMockRecorder) CreateWorkloadAssignments(ctx, claims, assignments any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWorkloadAssignments", reflect.TypeOf((*MockWorkloadAssignmentSvc)(nil).CreateWorkloadAssignments), ctx, claims, assignments)
}

// DeleteWorkloadAssignments mocks base method.
func (m *MockWorkloadAssignmentSvc) DeleteWorkloadAssignments(ctx context.Context, claims *jwt.Claims, ids []uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWorkloadAssignments", ctx, claims, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWorkloadAssignments indicates an expected call of DeleteWorkloadAssignments.
func (mr *MockWorkloadAssignmentSvcMockRecorder) DeleteWorkloadAssignments(ctx, claims, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWorkloadAssignments", reflect.TypeOf((*MockWorkloadAssignmentSvc)(nil).DeleteWorkloadAssignments), ctx, claims, ids)
}

// FetchWorkloadAssignments mocks base method.
func (m *MockWorkloadAssignmentSvc) FetchWorkloadAssignments(ctx context.Context, filters filter.Filters) (domain.WorkloadAssignments, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchWorkloadAssignments", ctx, filters)
	ret0, _ := ret[0].(domain.WorkloadAssignments)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchWorkloadAssignments indicates an expected call of FetchWorkloadAssignments.
func (mr *MockWorkloadAssignmentSvcMockRecorder) FetchWorkloadAssignments(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchWorkloadAssignments", reflect.TypeOf((*MockWorkloadAssignmentSvc)(nil).FetchWorkloadAssignments), ctx, filters)
}

// GetWorkloadAssignmentByID mocks base method.
func (m *MockWorkloadAssignmentSvc) GetWorkloadAssignmentByID(ctx context.Context, id uint64) (*domain.WorkloadAssignment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkloadAssignmentByID", ctx, id)
	ret0, _ := ret[0].(*domain.WorkloadAssignment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkloadAssignmentByID indicates an expected call of GetWorkloadAssignmentByID.
func (mr *MockWorkloadAssignmentSvcMockRecorder) GetWorkloadAssignmentByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkloadAssignmentByID", reflect.TypeOf((*MockWorkloadAssignmentSvc)(nil).GetWorkloadAssignmentByID), ctx, id)
}

// UpdateWorkloadAssignments mocks base method.
func (m *MockWorkloadAssignmentSvc) UpdateWorkloadAssignments(ctx context.Context, claims *jwt.Claims, assignments domain.WorkloadAssignments) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWorkloadAssignments", ctx, claims, assignments)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWorkloadAssignments indicates an expected call of UpdateWorkloadAssignments.
func (mr *MockWorkloadAssignmentSvcMockRecorder) UpdateWorkloadAssignments(ctx, claims, assignments any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWorkloadAssignments", reflect.TypeOf((*MockWorkloadAssignmentSvc)(nil).UpdateWorkloadAssignments), ctx, claims, assignments)
}

// MockScheduleTemplateSettingSvc is a mock of ScheduleTemplateSettingSvc interface.
type MockScheduleTemplateSettingSvc struct {
	ctrl     *gomock.Controller
	recorder *MockScheduleTemplateSettingSvcMockRecorder
	isgomock struct{}
}

// MockScheduleTemplateSettingSvcMockRecorder is the mock recorder for MockScheduleTemplateSettingSvc.
type MockScheduleTemplateSettingSvcMockRecorder struct {
	mock *MockScheduleTemplateSettingSvc
}

// NewMockScheduleTemplateSettingSvc creates a new mock instance.
func NewMockScheduleTemplateSettingSvc(ctrl *gomock.Controller) *MockScheduleTemplateSettingSvc {
	mock := &MockScheduleTemplateSettingSvc{ctrl: ctrl}
	mock.recorder = &MockScheduleTemplateSettingSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScheduleTemplateSettingSvc) EXPECT() *MockScheduleTemplateSettingSvcMockRecorder {
	return m.recorder
}

// CreateScheduleTemplateSettings mocks base method.
func (m *MockScheduleTemplateSettingSvc) CreateScheduleTemplateSettings(ctx context.Context, claims *jwt.Claims, settings domain.ScheduleTemplateSettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateScheduleTemplateSettings", ctx, claims, settings)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateScheduleTemplateSettings indicates an expected call of CreateScheduleTemplateSettings.
func (mr *MockScheduleTemplateSettingSvcMockRecorder) CreateScheduleTemplateSettings(ctx, claims, settings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateScheduleTemplateSettings", reflect.TypeOf((*MockScheduleTemplateSettingSvc)(nil).CreateScheduleTemplateSettings), ctx, claims, settings)
}

// DeleteScheduleTemplateSettings mocks base method.
func (m *MockScheduleTemplateSettingSvc) DeleteScheduleTemplateSettings(ctx context.Context, claims *jwt.Claims, ids []uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteScheduleTemplateSettings", ctx, claims, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteScheduleTemplateSettings indicates an expected call of DeleteScheduleTemplateSettings.
func (mr *MockScheduleTemplateSettingSvcMockRecorder) DeleteScheduleTemplateSettings(ctx, claims, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteScheduleTemplateSettings", reflect.TypeOf((*MockScheduleTemplateSettingSvc)(nil).DeleteScheduleTemplateSettings), ctx, claims, ids)
}

// FetchScheduleTemplateSettings mocks base method.
func (m *MockScheduleTemplateSettingSvc) FetchScheduleTemplateSettings(ctx context.Context, filters filter.Filters) (domain.ScheduleTemplateSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchScheduleTemplateSettings", ctx, filters)
	ret0, _ := ret[0].(domain.ScheduleTemplateSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchScheduleTemplateSettings indicates an expected call of FetchScheduleTemplateSettings.
func (mr *MockScheduleTemplateSettingSvcMockRecorder) FetchScheduleTemplateSettings(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchScheduleTemplateSettings", reflect.TypeOf((*MockScheduleTemplateSettingSvc)(nil).FetchScheduleTemplateSettings), ctx, filters)
}

// GetScheduleTemplateSettingByID mocks base method.
func (m *MockScheduleTemplateSettingSvc) GetScheduleTemplateSettingByID(ctx context.Context, id uint64) (*domain.ScheduleTemplateSetting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScheduleTemplateSettingByID", ctx, id)
	ret0, _ := ret[0].(*domain.ScheduleTemplateSetting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScheduleTemplateSettingByID indicates an expected call of GetScheduleTemplateSettingByID.
func (mr *MockScheduleTemplateSettingSvcMockRecorder) GetScheduleTemplateSettingByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScheduleTemplateSettingByID", reflect.TypeOf((*MockScheduleTemplateSettingSvc)(nil).GetScheduleTemplateSettingByID), ctx, id)
}

// UpdateScheduleTemplateSettings mocks base method.
func (m *MockScheduleTemplateSettingSvc) UpdateScheduleTemplateSettings(ctx context.Context, claims *jwt.Claims, settings domain.ScheduleTemplateSettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateScheduleTemplateSettings", ctx, claims, settings)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateScheduleTemplateSettings indicates an expected call of UpdateScheduleTemplateSettings.
func (mr *MockScheduleTemplateSettingSvcMockRecorder) UpdateScheduleTemplateSettings(ctx, claims, settings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateScheduleTemplateSettings", reflect.TypeOf((*MockScheduleTemplateSettingSvc)(nil).UpdateScheduleTemplateSettings), ctx, claims, settings)
}

// MockBellScheduleSvc is a mock of BellScheduleSvc interface.
type MockBellScheduleSvc struct {
	ctrl     *gomock.Controller
	recorder *MockBellScheduleSvcMockRecorder
	isgomock struct{}
}

// MockBellScheduleSvcMockRecorder is the mock recorder for MockBellScheduleSvc.
type MockBellScheduleSvcMockRecorder struct {
	mock *MockBellScheduleSvc
}

// NewMockBellScheduleSvc creates a new mock instance.
func NewMockBellScheduleSvc(ctrl *gomock.Controller) *MockBellScheduleSvc {
	mock := &MockBellScheduleSvc{ctrl: ctrl}
	mock.recorder = &MockBellScheduleSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBellScheduleSvc) EXPECT() *MockBellScheduleSvcMockRecorder {
	return m.recorder
}

// CreateBellSchedules mocks base method.
func (m *MockBellScheduleSvc) CreateBellSchedules(ctx context.Context, claims *jwt.Claims, schedules domain.BellSchedules) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBellSchedules", ctx, claims, schedules)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBellSchedules indicates an expected call of CreateBellSchedules.
func (mr *MockBellScheduleSvcMockRecorder) CreateBellSchedules(ctx, claims, schedules any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBellSchedules", reflect.TypeOf((*MockBellScheduleSvc)(nil).CreateBellSchedules), ctx, claims, schedules)
}

// DeleteBellSchedules mocks base method.
func (m *MockBellScheduleSvc) DeleteBellSchedules(ctx context.Context, claims *jwt.Claims, ids []uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBellSchedules", ctx, claims, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBellSchedules indicates an expected call of DeleteBellSchedules.
func (mr *MockBellScheduleSvcMockRecorder) DeleteBellSchedules(ctx, claims, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBellSchedules", reflect.TypeOf((*MockBellScheduleSvc)(nil).DeleteBellSchedules), ctx, claims, ids)
}

// FetchBellSchedules mocks base method.
func (m *MockBellScheduleSvc) FetchBellSchedules(ctx context.Context, filters filter.Filters) (domain.BellSchedules, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchBellSchedules", ctx, filters)
	ret0, _ := ret[0].(domain.BellSchedules)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchBellSchedules indicates an expected call of FetchBellSchedules.
func (mr *MockBellScheduleSvcMockRecorder) FetchBellSchedules(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchBellSchedules", reflect.TypeOf((*MockBellScheduleSvc)(nil).FetchBellSchedules), ctx, filters)
}

// GetBellScheduleByID mocks base method.
func (m *MockBellScheduleSvc) GetBellScheduleByID(ctx context.Context, id uint64) (*domain.BellSchedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBellScheduleByID", ctx, id)
	ret0, _ := ret[0].(*domain.BellSchedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBellScheduleByID indicates an expected call of GetBellScheduleByID.
func (mr *MockBellScheduleSvcMockRecorder) GetBellScheduleByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBellScheduleByID", reflect.TypeOf((*MockBellScheduleSvc)(nil).GetBellScheduleByID), ctx, id)
}

// UpdateBellSchedules mocks base method.
func (m *MockBellScheduleSvc) UpdateBellSchedules(ctx context.Context, claims *jwt.Claims, schedules domain.BellSchedules) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBellSchedules", ctx, claims, schedules)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBellSchedules indicates an expected call of UpdateBellSchedules.
func (mr *MockBellScheduleSvcMockRecorder) UpdateBellSchedules(ctx, claims, schedules any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBellSchedules", reflect.TypeOf((*MockBellScheduleSvc)(nil).UpdateBellSchedules), ctx, claims, schedules)
}

// MockScheduleTemplateSvc is a mock of ScheduleTemplateSvc interface.
type MockScheduleTemplateSvc struct {
	ctrl     *gomock.Controller
	recorder *MockScheduleTemplateSvcMockRecorder
	isgomock struct{}
}

// MockScheduleTemplateSvcMockRecorder is the mock recorder for MockScheduleTemplateSvc.
type MockScheduleTemplateSvcMockRecorder struct {
	mock *MockScheduleTemplateSvc
}

// NewMockScheduleTemplateSvc creates a new mock instance.
func NewMockScheduleTemplateSvc(ctrl *gomock.Controller) *MockScheduleTemplateSvc {
	mock := &MockScheduleTemplateSvc{ctrl: ctrl}
	mock.recorder = &MockScheduleTemplateSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScheduleTemplateSvc) EXPECT() *MockScheduleTemplateSvcMockRecorder {
	return m.recorder
}

// ActivateScheduleTemplate mocks base method.
func (m *MockScheduleTemplateSvc) ActivateScheduleTemplate(ctx context.Context, claims *jwt.Claims, id uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateScheduleTemplate", ctx, claims, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ActivateScheduleTemplate indicates an expected call of ActivateScheduleTemplate.
func (mr *MockScheduleTemplateSvcMockRecorder) ActivateScheduleTemplate(ctx, claims, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateScheduleTemplate", reflect.TypeOf((*MockScheduleTemplateSvc)(nil).ActivateScheduleTemplate), ctx, claims, id)
}

// DeleteScheduleTemplates mocks base method.
func (m *MockScheduleTemplateSvc) DeleteScheduleTemplates(ctx context.Context, claims *jwt.Claims, ids []uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteScheduleTemplates", ctx, claims, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteScheduleTemplates indicates an expected call of DeleteScheduleTemplates.
func (mr *MockScheduleTemplateSvcMockRecorder) DeleteScheduleTemplates(ctx, claims, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteScheduleTemplates", reflect.TypeOf((*MockScheduleTemplateSvc)(nil).DeleteScheduleTemplates), ctx, claims, ids)
}

// FetchScheduleTemplates mocks base method.
func (m *MockScheduleTemplateSvc) FetchScheduleTemplates(ctx context.Context, filters filter.Filters) (domain.ScheduleTemplates, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchScheduleTemplates", ctx, filters)
	ret0, _ := ret[0].(domain.ScheduleTemplates)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchScheduleTemplates indicates an expected call of FetchScheduleTemplates.
func (mr *MockScheduleTemplateSvcMockRecorder) FetchScheduleTemplates(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchScheduleTemplates", reflect.TypeOf((*MockScheduleTemplateSvc)(nil).FetchScheduleTemplates), ctx, filters)
}

// GenerateScheduleTemplate mocks base method.
func (m *MockScheduleTemplateSvc) GenerateScheduleTemplate(ctx context.Context, req *domain.GenerateScheduleRequest) (*domain.ScheduleData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateScheduleTemplate", ctx, req)
	ret0, _ := ret[0].(*domain.ScheduleData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateScheduleTemplate indicates an expected call of GenerateScheduleTemplate.
func (mr *MockScheduleTemplateSvcMockRecorder) GenerateScheduleTemplate(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateScheduleTemplate", reflect.TypeOf((*MockScheduleTemplateSvc)(nil).GenerateScheduleTemplate), ctx, req)
}

// GetScheduleTemplateByID mocks base method.
func (m *MockScheduleTemplateSvc) GetScheduleTemplateByID(ctx context.Context, id uint64) (*domain.ScheduleTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScheduleTemplateByID", ctx, id)
	ret0, _ := ret[0].(*domain.ScheduleTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScheduleTemplateByID indicates an expected call of GetScheduleTemplateByID.
func (mr *MockScheduleTemplateSvcMockRecorder) GetScheduleTemplateByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScheduleTemplateByID", reflect.TypeOf((*MockScheduleTemplateSvc)(nil).GetScheduleTemplateByID), ctx, id)
}

// SaveScheduleTemplate mocks base method.
func (m *MockScheduleTemplateSvc) SaveScheduleTemplate(ctx context.Context, claims *jwt.Claims, req *domain.SaveScheduleTemplateRequest) (*domain.ScheduleTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveScheduleTemplate", ctx, claims, req)
	ret0, _ := ret[0].(*domain.ScheduleTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveScheduleTemplate indicates an expected call of SaveScheduleTemplate.
func (mr *MockScheduleTemplateSvcMockRecorder) SaveScheduleTemplate(ctx, claims, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveScheduleTemplate", reflect.TypeOf((*MockScheduleTemplateSvc)(nil).SaveScheduleTemplate), ctx, claims, req)
}

// MockScheduleRestrictionSvc is a mock of ScheduleRestrictionSvc interface.
type MockScheduleRestrictionSvc struct {
	ctrl     *gomock.Controller
	recorder *MockScheduleRestrictionSvcMockRecorder
	isgomock struct{}
}

// MockScheduleRestrictionSvcMockRecorder is the mock recorder for MockScheduleRestrictionSvc.
type MockScheduleRestrictionSvcMockRecorder struct {
	mock *MockScheduleRestrictionSvc
}

// NewMockScheduleRestrictionSvc creates a new mock instance.
func NewMockScheduleRestrictionSvc(ctrl *gomock.Controller) *MockScheduleRestrictionSvc {
	mock := &MockScheduleRestrictionSvc{ctrl: ctrl}
	mock.recorder = &MockScheduleRestrictionSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScheduleRestrictionSvc) EXPECT() *MockScheduleRestrictionSvcMockRecorder {
	return m.recorder
}

// CreateScheduleRestrictions mocks base method.
func (m *MockScheduleRestrictionSvc) CreateScheduleRestrictions(ctx context.Context, claims *jwt.Claims, restrictions domain.ScheduleRestrictions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateScheduleRestrictions", ctx, claims, restrictions)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateScheduleRestrictions indicates an expected call of CreateScheduleRestrictions.
func (mr *MockScheduleRestrictionSvcMockRecorder) CreateScheduleRestrictions(ctx, claims, restrictions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateScheduleRestrictions", reflect.TypeOf((*MockScheduleRestrictionSvc)(nil).CreateScheduleRestrictions), ctx, claims, restrictions)
}

// DeleteScheduleRestrictions mocks base method.
func (m *MockScheduleRestrictionSvc) DeleteScheduleRestrictions(ctx context.Context, claims *jwt.Claims, ids []uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteScheduleRestrictions", ctx, claims, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteScheduleRestrictions indicates an expected call of DeleteScheduleRestrictions.
func (mr *MockScheduleRestrictionSvcMockRecorder) DeleteScheduleRestrictions(ctx, claims, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteScheduleRestrictions", reflect.TypeOf((*MockScheduleRestrictionSvc)(nil).DeleteScheduleRestrictions), ctx, claims, ids)
}

// FetchScheduleRestrictions mocks base method.
func (m *MockScheduleRestrictionSvc) FetchScheduleRestrictions(ctx context.Context, filters filter.Filters) (domain.ScheduleRestrictions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchScheduleRestrictions", ctx, filters)
	ret0, _ := ret[0].(domain.ScheduleRestrictions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchScheduleRestrictions indicates an expected call of FetchScheduleRestrictions.
func (mr *MockScheduleRestrictionSvcMockRecorder) FetchScheduleRestrictions(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchScheduleRestrictions", reflect.TypeOf((*MockScheduleRestrictionSvc)(nil).FetchScheduleRestrictions), ctx, filters)
}

// GetScheduleRestrictionByID mocks base method.
func (m *MockScheduleRestrictionSvc) GetScheduleRestrictionByID(ctx context.Context, id uint64) (*domain.ScheduleRestriction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScheduleRestrictionByID", ctx, id)
	ret0, _ := ret[0].(*domain.ScheduleRestriction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScheduleRestrictionByID indicates an expected call of GetScheduleRestrictionByID.
func (mr *MockScheduleRestrictionSvcMockRecorder) GetScheduleRestrictionByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScheduleRestrictionByID", reflect.TypeOf((*MockScheduleRestrictionSvc)(nil).GetScheduleRestrictionByID), ctx, id)
}

// UpdateScheduleRestrictions mocks base method.
func (m *MockScheduleRestrictionSvc) UpdateScheduleRestrictions(ctx context.Context, claims *jwt.Claims, restrictions domain.ScheduleRestrictions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateScheduleRestrictions", ctx, claims, restrictions)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateScheduleRestrictions indicates an expected call of UpdateScheduleRestrictions.
func (mr *MockScheduleRestrictionSvcMockRecorder) UpdateScheduleRestrictions(ctx, claims, restrictions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateScheduleRestrictions", reflect.TypeOf((*MockScheduleRestrictionSvc)(nil).UpdateScheduleRestrictions), ctx, claims, restrictions)
}

// MockUserSvc is a mock of UserSvc interface.
type MockUserSvc struct {
	ctrl     *gomock.Controller
	recorder *MockUserSvcMockRecorder
	isgomock struct{}
}

// MockUserSvcMockRecorder is the mock recorder for MockUserSvc.
type MockUserSvcMockRecorder struct {
	mock *MockUserSvc
}

// NewMockUserSvc creates a new mock instance.
func NewMockUserSvc(ctrl *gomock.Controller) *MockUserSvc {
	mock := &MockUserSvc{ctrl: ctrl}
	mock.recorder = &MockUserSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserSvc) EXPECT() *MockUserSvcMockRecorder {
	return m.recorder
}

// MassageConsumer mocks base method.
func (m *MockUserSvc) MassageConsumer(ctx context.Context, massage *domain.Massage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MassageConsumer", ctx, massage)
	ret0, _ := ret[0].(error)
	return ret0
}

// MassageConsumer indicates an expected call of MassageConsumer.
func (mr *MockUserSvcMockRecorder) MassageConsumer(ctx, massage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MassageConsumer", reflect.TypeOf((*MockUserSvc)(nil).MassageConsumer), ctx, massage)
}
