// Code generated by MockGen. DO NOT EDIT.
// Source: internal/user-management/service/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/user-management/service/interface.go -destination=internal/user-management/service/mocks/mock.go
//

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	reflect "reflect"

	jwt "github.com/Lapakin/edu-planner/internal/adapter/jwt"
	filter "github.com/Lapakin/edu-planner/internal/app/filter"
	domain "github.com/Lapakin/edu-planner/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockUserSvc is a mock of UserSvc interface.
type MockUserSvc struct {
	ctrl     *gomock.Controller
	recorder *MockUserSvcMockRecorder
	isgomock struct{}
}

// MockUserSvcMockRecorder is the mock recorder for MockUserSvc.
type MockUserSvcMockRecorder struct {
	mock *MockUserSvc
}

// NewMockUserSvc creates a new mock instance.
func NewMockUserSvc(ctrl *gomock.Controller) *MockUserSvc {
	mock := &MockUserSvc{ctrl: ctrl}
	mock.recorder = &MockUserSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserSvc) EXPECT() *MockUserSvcMockRecorder {
	return m.recorder
}

// ActivateUser mocks base method.
func (m *MockUserSvc) ActivateUser(ctx context.Context, claims *jwt.Claims, userID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateUser", ctx, claims, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ActivateUser indicates an expected call of ActivateUser.
func (mr *MockUserSvcMockRecorder) ActivateUser(ctx, claims, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateUser", reflect.TypeOf((*MockUserSvc)(nil).ActivateUser), ctx, claims, userID)
}

// AttachUsers mocks base method.
func (m *MockUserSvc) AttachUsers(ctx context.Context, academicYearID uint64, userIDs []uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachUsers", ctx, academicYearID, userIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// AttachUsers indicates an expected call of AttachUsers.
func (mr *MockUserSvcMockRecorder) AttachUsers(ctx, academicYearID, userIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachUsers", reflect.TypeOf((*MockUserSvc)(nil).AttachUsers), ctx, academicYearID, userIDs)
}

// CreateUsers mocks base method.
func (m *MockUserSvc) CreateUsers(ctx context.Context, claims *jwt.Claims, users domain.Users) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUsers", ctx, claims, users)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUsers indicates an expected call of CreateUsers.
func (mr *MockUserSvcMockRecorder) CreateUsers(ctx, claims, users any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUsers", reflect.TypeOf((*MockUserSvc)(nil).CreateUsers), ctx, claims, users)
}

// DeactivateUser mocks base method.
func (m *MockUserSvc) DeactivateUser(ctx context.Context, claims *jwt.Claims, userID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateUser", ctx, claims, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateUser indicates an expected call of DeactivateUser.
func (mr *MockUserSvcMockRecorder) DeactivateUser(ctx, claims, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateUser", reflect.TypeOf((*MockUserSvc)(nil).DeactivateUser), ctx, claims, userID)
}

// DeleteUsers mocks base method.
func (m *MockUserSvc) DeleteUsers(ctx context.Context, claims *jwt.Claims, userIDs []uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUsers", ctx, claims, userIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUsers indicates an expected call of DeleteUsers.
func (mr *MockUserSvcMockRecorder) DeleteUsers(ctx, claims, userIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUsers", reflect.TypeOf((*MockUserSvc)(nil).DeleteUsers), ctx, claims, userIDs)
}

// FetchUsers mocks base method.
func (m *MockUserSvc) FetchUsers(ctx context.Context, filters filter.Filters) (domain.Users, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchUsers", ctx, filters)
	ret0, _ := ret[0].(domain.Users)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchUsers indicates an expected call of FetchUsers.
func (mr *MockUserSvcMockRecorder) FetchUsers(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchUsers", reflect.TypeOf((*MockUserSvc)(nil).FetchUsers), ctx, filters)
}

// GetUserByID mocks base method.
func (m *MockUserSvc) GetUserByID(ctx context.Context, userID uint64) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, userID)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserSvcMockRecorder) GetUserByID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserSvc)(nil).GetUserByID), ctx, userID)
}

// UpdateUsers mocks base method.
func (m *MockUserSvc) UpdateUsers(ctx context.Context, claims *jwt.Claims, users domain.Users) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUsers", ctx, claims, users)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUsers indicates an expected call of UpdateUsers.
func (mr *MockUserSvcMockRecorder) UpdateUsers(ctx, claims, users any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUsers", reflect.TypeOf((*MockUserSvc)(nil).UpdateUsers), ctx, claims, users)
}

// MockAuthSvc is a mock of AuthSvc interface.
type MockAuthSvc struct {
	ctrl     *gomock.Controller
	recorder *MockAuthSvcMockRecorder
	isgomock struct{}
}

// MockAuthSvcMockRecorder is the mock recorder for MockAuthSvc.
type MockAuthSvcMockRecorder struct {
	mock *MockAuthSvc
}

// NewMockAuthSvc creates a new mock instance.
func NewMockAuthSvc(ctrl *gomock.Controller) *MockAuthSvc {
	mock := &MockAuthSvc{ctrl: ctrl}
	mock.recorder = &MockAuthSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthSvc) EXPECT() *MockAuthSvcMockRecorder {
	return m.recorder
}

// CreateInvite mocks base method.
func (m *MockAuthSvc) CreateInvite(ctx context.Context, claims *jwt.Claims, req domain.InviteReq) (*domain.InviteResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInvite", ctx, claims, req)
	ret0, _ := ret[0].(*domain.InviteResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInvite indicates an expected call of CreateInvite.
func (mr *MockAuthSvcMockRecorder) CreateInvite(ctx, claims, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInvite", reflect.TypeOf((*MockAuthSvc)(nil).CreateInvite), ctx, claims, req)
}

// GenerateResetPasswordLink mocks base method.
func (m *MockAuthSvc) GenerateResetPasswordLink(ctx context.Context, claims *jwt.Claims, userID uint64) (*domain.InviteResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateResetPasswordLink", ctx, claims, userID)
	ret0, _ := ret[0].(*domain.InviteResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateResetPasswordLink indicates an expected call of GenerateResetPasswordLink.
func (mr *MockAuthSvcMockRecorder) GenerateResetPasswordLink(ctx, claims, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateResetPasswordLink", reflect.TypeOf((*MockAuthSvc)(nil).GenerateResetPasswordLink), ctx, claims, userID)
}

// Login mocks base method.
func (m *MockAuthSvc) Login(ctx context.Context, email, password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, email, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockAuthSvcMockRecorder) Login(ctx, email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthSvc)(nil).Login), ctx, email, password)
}

// ResetInvite mocks base method.
func (m *MockAuthSvc) ResetInvite(ctx context.Context, claims *jwt.Claims, userID uint64) (*domain.InviteResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetInvite", ctx, claims, userID)
	ret0, _ := ret[0].(*domain.InviteResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResetInvite indicates an expected call of ResetInvite.
func (mr *MockAuthSvcMockRecorder) ResetInvite(ctx, claims, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetInvite", reflect.TypeOf((*MockAuthSvc)(nil).ResetInvite), ctx, claims, userID)
}

// ResetPassword mocks base method.
func (m *MockAuthSvc) ResetPassword(ctx context.Context, token, password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetPassword", ctx, token, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResetPassword indicates an expected call of ResetPassword.
func (mr *MockAuthSvcMockRecorder) ResetPassword(ctx, token, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetPassword", reflect.TypeOf((*MockAuthSvc)(nil).ResetPassword), ctx, token, password)
}

// SetPassword mocks base method.
func (m *MockAuthSvc) SetPassword(ctx context.Context, token, password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPassword", ctx, token, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetPassword indicates an expected call of SetPassword.
func (mr *MockAuthSvcMockRecorder) SetPassword(ctx, token, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPassword", reflect.TypeOf((*MockAuthSvc)(nil).SetPassword), ctx, token, password)
}

// MockAcademicYearSvc is a mock of AcademicYearSvc interface.
type MockAcademicYearSvc struct {
	ctrl     *gomock.Controller
	recorder *MockAcademicYearSvcMockRecorder
	isgomock struct{}
}

// MockAcademicYearSvcMockRecorder is the mock recorder for MockAcademicYearSvc.
type MockAcademicYearSvcMockRecorder struct {
	mock *MockAcademicYearSvc
}

// NewMockAcademicYearSvc creates a new mock instance.
func NewMockAcademicYearSvc(ctrl *gomock.Controller) *MockAcademicYearSvc {
	mock := &MockAcademicYearSvc{ctrl: ctrl}
	mock.recorder = &MockAcademicYearSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAcademicYearSvc) EXPECT() *MockAcademicYearSvcMockRecorder {
	return m.recorder
}

// MassageConsumer mocks base method.
func (m *MockAcademicYearSvc) MassageConsumer(ctx context.Context, massage *domain.Massage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MassageConsumer", ctx, massage)
	ret0, _ := ret[0].(error)
	return ret0
}

// MassageConsumer indicates an expected call of MassageConsumer.
func (mr *MockAcademicYearSvcMockRecorder) MassageConsumer(ctx, massage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MassageConsumer", reflect.TypeOf((*MockAcademicYearSvc)(nil).MassageConsumer), ctx, massage)
}
